/* Generated by bridgefex from "edge.h". Do not edit. */
#ifndef EDGE_EDGE_C_H
#define EDGE_EDGE_C_H

#include "edge_runtime.h"

/* Opaque handles. */
typedef struct edge_Registry edge_Registry;

#ifdef __cplusplus
extern "C" {
#endif

/* int edge::add(int, int) */
EDGE_NODISCARD EDGE_API edge_status edge_add(int arg1, int arg2, int* out_result);

/* int64_t edge::combine(int32_t int32_t, size_t size_t, int EDGE_OK) */
EDGE_NODISCARD EDGE_API edge_status edge_combine(int32_t int32_t_, size_t size_t_, int EDGE_OK_, int64_t* out_result);

/* int edge::getattr(int value) */
EDGE_NODISCARD EDGE_API edge_status edge_getattr(int value, int* out_result);

/* int edge::threading() */
EDGE_NODISCARD EDGE_API edge_status edge_threading(int* out_result);

/* edge::Registry::Registry() */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_create(edge_Registry** out_self);

/* edge::Registry::~Registry() */
EDGE_API void edge_Registry_destroy(edge_Registry* self);

/* int edge::Registry::classmethod() const */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_classmethod(const edge_Registry* self, int* out_result);

/* int edge::Registry::staticmethod() const */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_staticmethod(const edge_Registry* self, int* out_result);

/* void edge::Registry::throwOnDestroy(bool enabled) */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_throwOnDestroy(edge_Registry* self, bool enabled);

/* void edge::Registry::fail() const */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_fail(const edge_Registry* self);

/* static int edge::Registry::liveCount() */
EDGE_NODISCARD EDGE_API edge_status edge_Registry_liveCount(int* out_result);

#ifdef __cplusplus
}
#endif

#endif /* EDGE_EDGE_C_H */
