// Generated by bridgefex from "edge.h". Do not edit.
#ifndef EDGE_C_API_BUILD
#define EDGE_C_API_BUILD
#endif

// The standard headers that the generated code needs come before the wrapped
// header, so that its macros cannot change them.
#include <cstddef>
#include <exception>
#include <new>
#if defined(__GLIBCXX__)
#include <bits/cxxabi_forced.h>
#endif

// The wrapped header comes before the generated ones: a global C++ declaration
// that clashed with a generated C function would then be a compile error, not a
// silent redirection.
#include "edge.h"

#include "edge_c.h"
#include "edge_runtime_internal.hpp"

#if !defined(__cpp_aligned_new)
// Before C++17, new ignores alignments larger than the default one of the
// platform's operator new.
namespace edge_detail {
#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
constexpr std::size_t new_alignment = __STDCPP_DEFAULT_NEW_ALIGNMENT__;
#elif defined(_MSC_VER) && defined(_WIN64)
constexpr std::size_t new_alignment = 16;  // std::max_align_t is double there
#else
constexpr std::size_t new_alignment = alignof(std::max_align_t);
#endif
}  // namespace edge_detail
static_assert(alignof(::edge::Registry) <= edge_detail::new_alignment,
              "edge::Registry is over-aligned: compile this file as C++17 or later");
#endif

extern "C" {

// int edge::add(int, int)
edge_status edge_add(int arg1, int arg2, int* out_result)
{
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_add: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = ::edge::add(arg1, arg2); });
}

// int64_t edge::combine(int32_t int32_t, size_t size_t, int EDGE_OK)
edge_status edge_combine(int32_t int32_t_, size_t size_t_, int EDGE_OK_, int64_t* out_result)
{
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_combine: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = ::edge::combine(int32_t_, size_t_, EDGE_OK_); });
}

// int edge::getattr(int value)
edge_status edge_getattr(int value, int* out_result)
{
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_getattr: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = ::edge::getattr(value); });
}

// int edge::threading()
edge_status edge_threading(int* out_result)
{
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_threading: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = ::edge::threading(); });
}

// edge::Registry::Registry()
edge_status edge_Registry_create(edge_Registry** out_self)
{
    if (out_self == nullptr) {
        return edge_detail::null_argument("edge_Registry_create: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return edge_detail::guard([&]() { *out_self = reinterpret_cast<edge_Registry*>(new ::edge::Registry()); });
}

// edge::Registry::~Registry()
void edge_Registry_destroy(edge_Registry* self)
{
    // A destructor that throws cannot report it here, and last_error is left
    // alone because a failed call may not have been inspected yet.
    edge_detail::guard_silently([&]() { delete reinterpret_cast<::edge::Registry*>(self); });
}

// int edge::Registry::classmethod() const
edge_status edge_Registry_classmethod(const edge_Registry* self, int* out_result)
{
    if (self == nullptr) {
        return edge_detail::null_argument("edge_Registry_classmethod: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_Registry_classmethod: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = reinterpret_cast<const ::edge::Registry*>(self)->classmethod(); });
}

// int edge::Registry::staticmethod() const
edge_status edge_Registry_staticmethod(const edge_Registry* self, int* out_result)
{
    if (self == nullptr) {
        return edge_detail::null_argument("edge_Registry_staticmethod: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_Registry_staticmethod: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = reinterpret_cast<const ::edge::Registry*>(self)->staticmethod(); });
}

// void edge::Registry::throwOnDestroy(bool enabled)
edge_status edge_Registry_throwOnDestroy(edge_Registry* self, bool enabled)
{
    if (self == nullptr) {
        return edge_detail::null_argument("edge_Registry_throwOnDestroy: 'self' is NULL");
    }
    return edge_detail::guard([&]() { reinterpret_cast<::edge::Registry*>(self)->throwOnDestroy(enabled); });
}

// void edge::Registry::fail() const
edge_status edge_Registry_fail(const edge_Registry* self)
{
    if (self == nullptr) {
        return edge_detail::null_argument("edge_Registry_fail: 'self' is NULL");
    }
    return edge_detail::guard([&]() { reinterpret_cast<const ::edge::Registry*>(self)->fail(); });
}

// static int edge::Registry::liveCount()
edge_status edge_Registry_liveCount(int* out_result)
{
    if (out_result == nullptr) {
        return edge_detail::null_argument("edge_Registry_liveCount: 'out_result' is NULL");
    }
    return edge_detail::guard([&]() { *out_result = ::edge::Registry::liveCount(); });
}

}  // extern "C"
