// Generated by bridgefex. Do not edit.
#ifndef EDGE_C_API_BUILD
#define EDGE_C_API_BUILD
#endif

#include "edge_runtime.h"
#include "edge_runtime_internal.hpp"

#include <cstddef>
#include <cstring>

namespace {

// Longer messages are truncated.
const std::size_t kMaxMessageSize = 1024;

thread_local char last_error_message[kMaxMessageSize];

}  // namespace

namespace edge_detail {

void set_last_error(const char* message) noexcept
{
    if (message == nullptr) {
        message = "";
    }
    std::size_t length = std::strlen(message);
    if (length >= kMaxMessageSize) {
        length = kMaxMessageSize - 1;
        // Do not cut a UTF-8 sequence in half.
        while (length > 0 && (static_cast<unsigned char>(message[length]) & 0xC0u) == 0x80u) {
            --length;
        }
    }
    std::memcpy(last_error_message, message, length);
    last_error_message[length] = '\0';
}

}  // namespace edge_detail

extern "C" const char* edge_last_error(void)
{
    return last_error_message;
}

extern "C" const char* edge_api_fingerprint(void)
{
    return "5c8b9f4c48ca7691c2f163a922126717";
}
