# SPDX-License-Identifier: Apache-2.0
"""Generation from adversarial headers: every result must be rejected clearly or be correct.

Unlike test_rejections.py (the parser alone), these tests run the whole
pipeline: parser, naming checks and the libclang verification of the
generated code.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
from clang import cindex

import bridgefex
from bridgefex.errors import BridgefexError, ConfigurationError, GenerationError

pytestmark = pytest.mark.usefixtures("libclang_loaded")

PRELUDE = "#pragma once\n#include <cstddef>\n#include <cstdint>\n#include <functional>\n"


def write_header(directory: Path, code: str, name: str = "api.h") -> Path:
    path = directory / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PRELUDE + code + "\n", encoding="utf-8")
    return path


def generate(directory: Path, code: str, std: str = "c++17") -> bridgefex.Result:
    return bridgefex.generate([write_header(directory, code)], bridgefex.Options("mod", std=std))


def error_of(directory: Path, code: str, std: str = "c++17") -> str:
    with pytest.raises(BridgefexError) as raised:
        generate(directory, code, std)
    return str(raised.value)


@pytest.mark.parametrize(
    ("code", "message"),
    [
        # Types spelled like the standard ones but declared by the user.
        (
            "namespace emb { typedef unsigned int size_t; size_t echo(size_t n); }",
            "type alias 'emb::size_t' is not supported",
        ),
        (
            "namespace emb { typedef long long int64_t; int kind(int64_t v); int kind(long v); }",
            "type alias 'emb::int64_t' is not supported",
        ),
        (
            "namespace sv { class Vec { public: using size_t = std::uint16_t;"
            " void resize(size_t n); }; }",
            "type alias 'sv::Vec::size_t' is not supported",
        ),
        (
            "namespace emb { using int32_t = long; int f(const int32_t v); }",
            "type alias 'const emb::int32_t' is not supported",
        ),
        # Generated C names that clash with what the headers declare.
        (
            "namespace a { void reset(); }\nstd::int32_t a_reset();",
            "the C name 'a_reset' of function 'a::reset()' clashes with a global declaration",
        ),
        (
            "namespace geo { class Point { public: int x() const; }; }\n"
            "namespace geo_Point { int dims(); }",
            "the C name 'geo_Point' of the handle type of 'geo::Point' clashes",
        ),
        (
            "#define MOD_API\nnamespace z { MOD_API int answer(); }",
            "the C name 'MOD_API' of a macro generated by bridgefex clashes with a macro",
        ),
        ("namespace MOD { int OK(int a); }", "'MOD_OK' of function 'MOD::OK(int a)' clashes"),
        ("namespace mod { void detail(); }", "clashes with the namespace of the generated C++"),
        ("namespace co { void yield(); }", "the C name 'co_yield' of function"),
        ("namespace thread { int local(); }", "is a C or C++ keyword"),
        ("namespace impl_ { int rpm(); }", "'impl__rpm' of function 'impl_::rpm()' is a reserved"),
        (
            "namespace _impl { int f(int a); }",
            "'_impl_f' of function '_impl::f(int a)' is a reserved",
        ),
        # Classes that cannot be used through new and delete.
        (
            "namespace k { class W { public: int get() const;"
            " private: std::reference_wrapper<int> r_; }; }",
            "the generated wrapper k_W_create() for 'k::W::W()' does not compile",
        ),
        (
            "namespace k { class T { template <class U> explicit T(U u);"
            " public: int get() const; }; }",
            "class 'k::T' has no public constructor",
        ),
        (
            "namespace al { class S { public: S(); int get() const;"
            " static void* operator new(std::size_t) = delete; }; }",
            "call to deleted function 'operator new'",
        ),
        (
            "namespace al { class P { public: P(); int get() const;"
            " private: static void* operator new(std::size_t); }; }",
            "the generated wrapper al_P_create() for 'al::P::P()' does not compile",
        ),
        (
            "namespace pm { class Task { public: int run() const;"
            " protected: virtual int step() const; }; }",
            "has virtual methods but no virtual destructor",
        ),
        # Calls that would be ambiguous because of default arguments.
        (
            "namespace d { class Box { public: Box(); explicit Box(int start = 0);"
            " int get() const; }; }",
            "the generated wrapper d_Box_create_void() for 'd::Box::Box()' does not compile",
        ),
        (
            "namespace d { int pick(); int pick(int x = 3); }",
            "the generated wrapper d_pick_void() for 'int d::pick()' does not compile",
        ),
    ],
)
def test_rejected(tmp_path: Path, code: str, message: str) -> None:
    assert message in error_of(tmp_path, code)


def test_consteval_is_rejected(tmp_path: Path) -> None:
    error = error_of(
        tmp_path, "namespace e { consteval int square(int x) { return x * x; } }", "c++20"
    )
    assert "the generated wrapper e_square() for 'int e::square(int x)' does not compile" in error


def test_explicit_object_parameter_is_rejected(tmp_path: Path) -> None:
    error = error_of(
        tmp_path,
        "namespace f { class S { public: int twice(this int self) { return 2 * self; }"
        " private: operator int() const { return 21; } }; }",
        "c++23",
    )
    assert "the generated wrapper f_S_twice()" in error


def test_verification_errors_point_at_the_wrapped_declaration(tmp_path: Path) -> None:
    error = error_of(tmp_path, "namespace d { int pick(); int pick(int x = 3); }")
    # PRELUDE has 4 lines, so the declaration is on line 5.
    assert error.startswith(f"{tmp_path / 'api.h'}:5:")


def test_verification_can_be_disabled(tmp_path: Path) -> None:
    header = write_header(tmp_path, "namespace d { int pick(); int pick(int x = 3); }")
    options = bridgefex.Options("mod", verify=False)
    assert "c/api_c.cpp" in bridgefex.generate([header], options).files


def test_warnings_of_generated_code_are_reported(tmp_path: Path) -> None:
    result = generate(tmp_path, "namespace o { [[deprecated]] int old(); }")
    assert any(
        "the generated wrapper o_old()" in str(warning) and "deprecated" in str(warning)
        for warning in result.warnings
    ), result.warnings


@pytest.mark.parametrize(
    ("code", "expected"),
    [
        # An unnamed struct named through a typedef.
        ("namespace tg { typedef struct { } Tag; }", "typedef struct tg_Tag tg_Tag;"),
        # Parameters named like a type or like a generated macro are renamed.
        ("namespace p { std::int32_t f(std::int32_t int32_t); }", "int32_t int32_t_"),
        ("namespace p { int f(int MOD_C_API_BUILD); }", "int MOD_C_API_BUILD_"),
        ("namespace p { int f(int unix, int pascal); }", "int unix_, int pascal_"),
        # ... and so are parameters named like a macro without arguments of the
        # translation unit, wherever it is defined, or like an include guard.
        ("namespace m { int scale(int value, int factor); }\n#define factor 3", "int factor_"),
        ("namespace m { int f(); int f(int X); }\n#define X", "int X_,"),
        ("namespace m { int f(); int f(int MOD_API_C_H); }", "int MOD_API_C_H_,"),
        ("#define max(a, b) a\nnamespace m { int f(int max); }", "int max,"),
        # ... even after an #undef (the <windows.h> min/max pattern).
        (
            "#define min(a, b) a\n#define max(a, b) b\n#undef min\n#undef max\n"
            "namespace m { int clamp(int value, int min, int max); }",
            "int value, int min, int max,",
        ),
        ("#include <cmath>\nnamespace m { bool classify(double isnan); }", "double isnan,"),
        # Macros of the C library that C programs may include: with <complex.h>,
        # 'double complex' would declare an unnamed 'double _Complex' parameter.
        ("namespace m { double mix(double complex, double I); }", "double complex_, double I_"),
        # A global 'abi' does not clash with what the generated code includes.
        ("int abi(int x);\nnamespace abi2 { int g(); }", "mod_abi(int x"),
        ("namespace abi { int f(); }", "abi_f("),
        # Redeclaring a standard typedef with the same type keeps it standard.
        ("typedef int int32_t;\nnamespace r { int32_t f(int32_t a); }", "r_f(int32_t a"),
        ("typedef decltype(sizeof 0) size_t;\nnamespace r { size_t f(); }", "size_t* out_result"),
        # Functions declared through a function type.
        ("namespace t { typedef int Op(int, int); Op add; }", "t_add(int arg1, int arg2"),
        # Final polymorphic classes are fine.
        (
            "namespace pm { class Task final { public: int run() const;"
            " private: virtual int step() const; }; }",
            "pm_Task_run(",
        ),
    ],
)
def test_accepted(tmp_path: Path, code: str, expected: str) -> None:
    assert expected in generate(tmp_path, code).files["c/api_c.h"]


def test_header_names_that_replace_package_names(tmp_path: Path) -> None:
    header = write_header(tmp_path, "namespace lb { int weight(); }", name="load.h")
    with pytest.raises(ConfigurationError, match="would replace 'load'"):
        bridgefex.generate([header], bridgefex.Options("mod"))


def test_header_names_that_differ_only_in_case(tmp_path: Path) -> None:
    first = write_header(tmp_path / "a", "namespace sa { int sides(); }", name="Shape.h")
    second = write_header(tmp_path / "b", "namespace sb { int area(); }", name="shape.h")
    with pytest.raises(GenerationError, match="same name \\(ignoring case\\)"):
        bridgefex.generate([first, second], bridgefex.Options("mod"))


@pytest.mark.skipif(sys.platform == "win32", reason="Windows forbids '*' and CR in file names")
@pytest.mark.parametrize("directory", ["v2*", "a\rb"])
def test_unsafe_include_paths(tmp_path: Path, directory: str) -> None:
    root = tmp_path / "include"
    header = write_header(root / directory, "namespace s { int f(); }")
    if directory == "v2*":
        # Only '*/' is unsafe; 'v2*' followed by '/api.h' makes it.
        assert "*/" in (Path(directory) / "api.h").as_posix()
    with pytest.raises(ConfigurationError, match="cannot write an #include"):
        bridgefex.generate([header], bridgefex.Options("mod", include_root=root))


@pytest.mark.parametrize("name", ["car_", "a__b"])
def test_module_names_that_make_reserved_identifiers(name: str) -> None:
    with pytest.raises(ConfigurationError, match="invalid module name"):
        bridgefex.generate([Path("x.h")], bridgefex.Options(name))


@pytest.mark.parametrize(
    "include",
    [
        pytest.param(
            "cstdint",
            marks=pytest.mark.skipif(
                sys.platform == "win32",
                reason="MSVC's <cstdint> does not declare std::size_t (nor must it)",
            ),
        ),
        "array",
        "utility",
        "type_traits",
        "new",
    ],
)
def test_std_size_t_without_the_global_one(tmp_path: Path, include: str) -> None:
    """libstdc++ declares std::size_t in namespace std; ::size_t needs <stddef.h>."""
    header = tmp_path / "sz.h"
    header.write_text(
        f"#pragma once\n#include <{include}>\nnamespace z {{ std::size_t f(std::size_t a); }}\n",
        encoding="utf-8",
    )
    result = bridgefex.generate([header], bridgefex.Options("mod"))
    assert "z_f(size_t a, size_t* out_result)" in result.files["c/sz_c.h"]


@pytest.mark.skipif(sys.platform == "win32", reason="a libstdc++ configuration macro")
def test_configuration_macros_of_the_wrapped_header_apply_to_the_generated_source(
    tmp_path: Path,
) -> None:
    """The wrapped header comes first in the generated source, as in the library's
    own sources: here std::string must be the old-ABI one in both."""
    header = tmp_path / "named.h"
    header.write_text(
        "#pragma once\n#define _GLIBCXX_USE_CXX11_ABI 0\n#include <string>\n"
        "namespace n { class Named { public: Named(); int size() const;"
        " private: std::string name_; }; }\n",
        encoding="utf-8",
    )
    # Verification compiles the generated source: with a standard header
    # before named.h, std::string would be ambiguous there.
    source = bridgefex.generate([header], bridgefex.Options("mod")).files["c/named_c.cpp"]
    includes = [line for line in source.splitlines() if line.startswith("#include")]
    assert includes[0] == '#include "named.h"'


@pytest.mark.skipif(sys.platform == "win32", reason="MSVC's <exception> declares std::byte")
@pytest.mark.parametrize(
    "code",
    [
        "#define byte unsigned char\n",
        "#include <cstdio>\nusing namespace std;\ntypedef unsigned char byte;\n",
    ],
)
def test_the_generated_code_does_not_declare_std_byte(tmp_path: Path, code: str) -> None:
    header = tmp_path / "bt.h"
    header.write_text(
        f"#pragma once\n{code}class Buf {{ public: Buf(); int size() const;"
        " private: byte data_[4]; };\n",
        encoding="utf-8",
    )
    result = bridgefex.generate([header], bridgefex.Options("mod", std="c++17"))
    assert "mod_Buf_size(" in result.files["c/bt_c.h"]


def test_library_headers_named_like_standard_headers(tmp_path: Path) -> None:
    """A time.h next to the wrapped header must not replace <time.h>."""
    directory = tmp_path / "include" / "lib"
    directory.mkdir(parents=True)
    (directory / "time.h").write_text(
        "#pragma once\nnamespace lib { class Duration { public: int ms() const; }; }\n",
        encoding="utf-8",
    )
    header = directory / "clock.h"
    header.write_text(
        '#pragma once\n#include <cstdint>\n#include <ctime>\n#include "time.h"\n'
        "namespace lib { class Clock { public: Clock(); std::int64_t now() const; }; }\n",
        encoding="utf-8",
    )
    result = bridgefex.generate([header], bridgefex.Options("mod"))
    assert "lib_Clock_now(" in result.files["c/clock_c.h"]
    # -I, the only option of MSVC, would let it replace <time.h>.
    (warning,) = (str(w) for w in result.warnings if "standard header" in str(w))
    assert "time.h has the name of a standard header" in warning
    assert "-iquote" in warning
    rooted = bridgefex.Options("mod", include_root=tmp_path / "include")
    assert not [w for w in bridgefex.generate([header], rooted).warnings if "standard" in str(w)]


@pytest.mark.parametrize("werror", ["-Werror", "-Werror=unused-variable"])
def test_werror_does_not_reject_warnings_of_the_wrapped_header(tmp_path: Path, werror: str) -> None:
    header = write_header(tmp_path, "namespace w { inline int h(int x) { int unused; return x; } }")
    result = bridgefex.generate([header], bridgefex.Options("mod", clang_args=(werror,)))
    assert "w_h(int x" in result.files["c/api_c.h"]


def test_functions_used_but_never_defined_are_reported(tmp_path: Path) -> None:
    result = generate(tmp_path, "static int hidden(int x);")
    assert any(
        "the generated wrapper mod_hidden()" in str(warning) and "not defined" in str(warning)
        for warning in result.warnings
    ), result.warnings


def test_libclang_failures_during_verification_are_errors(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    header = write_header(tmp_path, "namespace f { int g(); }")

    # Only verification parses a .cpp file.
    original = cindex.Index.parse

    def parse(self: cindex.Index, path: str, *args: object, **kwargs: object) -> object:
        if path.endswith(".cpp"):
            raise cindex.TranslationUnitLoadError("Error parsing translation unit.")
        return original(self, path, *args, **kwargs)  # type: ignore[arg-type]

    monkeypatch.setattr(cindex.Index, "parse", parse)
    with pytest.raises(GenerationError, match="libclang cannot compile the generated file api_c"):
        bridgefex.generate([header], bridgefex.Options("mod"))


@pytest.mark.parametrize("std", ["c++98", "c++03", "gnu++98", "gnu++03"])
def test_standards_before_cxx11_are_rejected(tmp_path: Path, std: str) -> None:
    with pytest.raises(ConfigurationError, match="needs C\\+\\+11 or later"):
        generate(tmp_path, "namespace o { int add(int a, int b); }", std)


@pytest.mark.parametrize(
    "clang_args",
    [("-std=c++03",), ("--std=gnu++98",), ("--std", "c++98"), ("-std=c++20", "-std=c++03")],
)
def test_standards_before_cxx11_are_rejected_in_clang_args(
    tmp_path: Path, clang_args: tuple[str, ...]
) -> None:
    """The last -std wins, also when it comes from --clang-arg."""
    header = write_header(tmp_path, "namespace o { int add(int a, int b); }")
    with pytest.raises(ConfigurationError, match="needs C\\+\\+11 or later"):
        bridgefex.generate([header], bridgefex.Options("mod", clang_args=clang_args))


def test_names_of_the_c_library_are_reserved(tmp_path: Path) -> None:
    """Even when the wrapped header does not include the library header."""
    header = tmp_path / "quick.h"
    header.write_text("#pragma once\nnamespace quick { void exit(int code); }\n", encoding="utf-8")
    with pytest.raises(
        GenerationError,
        match=r"'quick_exit' .* clashes with a global declaration of the system headers",
    ):
        bridgefex.generate([header], bridgefex.Options("mod"))


@pytest.mark.skipif(not sys.platform.startswith("linux"), reason="POSIX names of glibc")
@pytest.mark.parametrize(
    ("code", "name"),
    [
        ("namespace sched { int yield(); }", "sched_yield"),
        ("namespace epoll { int create(int size); }", "epoll_create"),
        ("namespace TCP { int NODELAY(); }", "TCP_NODELAY"),
    ],
)
def test_posix_names_are_reserved(tmp_path: Path, code: str, name: str) -> None:
    header = tmp_path / "tasks.h"
    header.write_text(f"#pragma once\n{code}\n", encoding="utf-8")
    with pytest.raises(GenerationError, match=rf"'{name}' .* of the system headers"):
        bridgefex.generate([header], bridgefex.Options("mod"))


@pytest.mark.skipif(sys.platform != "win32", reason="names of <windows.h>")
def test_windows_names_are_reserved(tmp_path: Path) -> None:
    """Module 's' would define S_OK, which <windows.h> defines too."""
    header = tmp_path / "api.h"
    header.write_text("#pragma once\nnamespace w { int f(); }\n", encoding="utf-8")
    with pytest.raises(GenerationError, match=r"'S_OK' .* clashes with a macro of the system"):
        bridgefex.generate([header], bridgefex.Options("s"))


@pytest.mark.parametrize(
    "names",
    [("mod_runtime.h",), ("mod_runtime_internal.hpp",), ("a.h", "a_c.h"), ("Mod_Runtime.h",)],
)
def test_headers_named_like_generated_files(tmp_path: Path, names: tuple[str, ...]) -> None:
    headers = [
        write_header(tmp_path, f"namespace n{i} {{ int f(); }}", name=name)
        for i, name in enumerate(names)
    ]
    with pytest.raises(GenerationError, match="has the name of a generated file"):
        bridgefex.generate(headers, bridgefex.Options("mod"))


def test_a_directory_avoids_the_names_of_generated_files(tmp_path: Path) -> None:
    root = tmp_path / "include"
    header = write_header(root / "lib", "namespace n { int f(); }", name="mod_runtime.h")
    result = bridgefex.generate([header], bridgefex.Options("mod", include_root=root))
    assert '#include "lib/mod_runtime.h"' in result.files["c/mod_runtime_c.cpp"]


@pytest.mark.skipif(sys.platform == "win32", reason="symbolic links need privileges on Windows")
def test_include_root_with_symbolic_links(tmp_path: Path) -> None:
    real = write_header(tmp_path / "real", "namespace w { int f(); }", name="w.h")
    linked = tmp_path / "inc" / "lib" / "w.h"
    linked.parent.mkdir(parents=True)
    linked.symlink_to(real)
    result = bridgefex.generate([linked], bridgefex.Options("mod", include_root=tmp_path / "inc"))
    assert '#include "lib/w.h"' in result.files["c/w_c.cpp"]


@pytest.mark.skipif(sys.platform == "win32", reason="symbolic links need privileges on Windows")
def test_include_root_does_not_drop_dot_dot_after_a_symbolic_link(tmp_path: Path) -> None:
    """inc/detail/../api.h is vendor/v2/api.h when inc/detail links into vendor/v2."""
    write_header(tmp_path / "inc", "namespace old_api { int legacy(); }")
    real = write_header(tmp_path / "vendor" / "v2", "namespace api { int version(); }")
    (real.parent / "detail").mkdir()
    (tmp_path / "inc" / "detail").symlink_to(real.parent / "detail")
    header = tmp_path / "inc" / "detail" / ".." / "api.h"
    with pytest.raises(ConfigurationError, match="not inside the include root"):
        bridgefex.generate([header], bridgefex.Options("mod", include_root=tmp_path / "inc"))
