# SPDX-License-Identifier: Apache-2.0
"""Generation from adversarial headers: every result must be rejected clearly or be correct.

Unlike test_rejections.py (the parser alone), these tests run the whole
pipeline: parser, naming checks and the libclang verification of the
generated code.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import bridgefex
from bridgefex.errors import BridgefexError, ConfigurationError, GenerationError

pytestmark = pytest.mark.usefixtures("libclang_loaded")

PRELUDE = "#pragma once\n#include <cstddef>\n#include <cstdint>\n#include <functional>\n"


def write_header(directory: Path, code: str, name: str = "api.h") -> Path:
    path = directory / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PRELUDE + code + "\n", encoding="utf-8")
    return path


def generate(directory: Path, code: str, std: str = "c++17") -> bridgefex.Result:
    return bridgefex.generate([write_header(directory, code)], bridgefex.Options("mod", std=std))


def error_of(directory: Path, code: str, std: str = "c++17") -> str:
    with pytest.raises(BridgefexError) as raised:
        generate(directory, code, std)
    return str(raised.value)


@pytest.mark.parametrize(
    ("code", "message"),
    [
        # Types spelled like the standard ones but declared by the user.
        (
            "namespace emb { typedef unsigned int size_t; size_t echo(size_t n); }",
            "type alias 'emb::size_t' is not supported",
        ),
        (
            "namespace emb { typedef long long int64_t; int kind(int64_t v); int kind(long v); }",
            "type alias 'emb::int64_t' is not supported",
        ),
        (
            "namespace sv { class Vec { public: using size_t = std::uint16_t;"
            " void resize(size_t n); }; }",
            "type alias 'sv::Vec::size_t' is not supported",
        ),
        (
            "namespace emb { using int32_t = long; int f(const int32_t v); }",
            "type alias 'const emb::int32_t' is not supported",
        ),
        # Generated C names that clash with what the headers declare.
        (
            "namespace a { void reset(); }\nstd::int32_t a_reset();",
            "the C name 'a_reset' of function 'a::reset()' clashes with a global declaration",
        ),
        (
            "namespace geo { class Point { public: int x() const; }; }\n"
            "namespace geo_Point { int dims(); }",
            "the C name 'geo_Point' of the handle type of 'geo::Point' clashes",
        ),
        (
            "#define MOD_API\nnamespace z { MOD_API int answer(); }",
            "the C name 'MOD_API' of a macro generated by bridgefex clashes with a macro",
        ),
        ("namespace MOD { int OK(int a); }", "'MOD_OK' of function 'MOD::OK(int a)' clashes"),
        ("namespace mod { void detail(); }", "clashes with the namespace of the generated C++"),
        ("namespace co { void yield(); }", "the C name 'co_yield' of function"),
        ("namespace thread { int local(); }", "is a C or C++ keyword"),
        ("namespace impl_ { int rpm(); }", "'impl__rpm' of function 'impl_::rpm()' is a reserved"),
        # Classes that cannot be used through new and delete.
        (
            "namespace k { class W { public: int get() const;"
            " private: std::reference_wrapper<int> r_; }; }",
            "the generated wrapper k_W_create() for 'k::W::W()' does not compile",
        ),
        (
            "namespace k { class T { template <class U> explicit T(U u);"
            " public: int get() const; }; }",
            "class 'k::T' has no public constructor",
        ),
        (
            "namespace al { class S { public: S(); int get() const;"
            " static void* operator new(std::size_t) = delete; }; }",
            "call to deleted function 'operator new'",
        ),
        (
            "namespace al { class P { public: P(); int get() const;"
            " private: static void* operator new(std::size_t); }; }",
            "the generated wrapper al_P_create() for 'al::P::P()' does not compile",
        ),
        (
            "namespace pm { class Task { public: int run() const;"
            " protected: virtual int step() const; }; }",
            "has virtual methods but no virtual destructor",
        ),
        # Calls that would be ambiguous because of default arguments.
        (
            "namespace d { class Box { public: Box(); explicit Box(int start = 0);"
            " int get() const; }; }",
            "the generated wrapper d_Box_create_void() for 'd::Box::Box()' does not compile",
        ),
        (
            "namespace d { int pick(); int pick(int x = 3); }",
            "the generated wrapper d_pick_void() for 'int d::pick()' does not compile",
        ),
    ],
)
def test_rejected(tmp_path: Path, code: str, message: str) -> None:
    assert message in error_of(tmp_path, code)


def test_consteval_is_rejected(tmp_path: Path) -> None:
    error = error_of(
        tmp_path, "namespace e { consteval int square(int x) { return x * x; } }", "c++20"
    )
    assert "the generated wrapper e_square() for 'int e::square(int x)' does not compile" in error


def test_explicit_object_parameter_is_rejected(tmp_path: Path) -> None:
    error = error_of(
        tmp_path,
        "namespace f { class S { public: int twice(this int self) { return 2 * self; }"
        " private: operator int() const { return 21; } }; }",
        "c++23",
    )
    assert "the generated wrapper f_S_twice()" in error


def test_verification_errors_point_at_the_wrapped_declaration(tmp_path: Path) -> None:
    error = error_of(tmp_path, "namespace d { int pick(); int pick(int x = 3); }")
    # PRELUDE has 4 lines, so the declaration is on line 5.
    assert error.startswith(f"{tmp_path / 'api.h'}:5:")


def test_verification_can_be_disabled(tmp_path: Path) -> None:
    header = write_header(tmp_path, "namespace d { int pick(); int pick(int x = 3); }")
    options = bridgefex.Options("mod", verify=False)
    assert "c/api_c.cpp" in bridgefex.generate([header], options).files


def test_warnings_of_generated_code_are_reported(tmp_path: Path) -> None:
    result = generate(tmp_path, "namespace o { [[deprecated]] int old(); }")
    assert any(
        "the generated wrapper o_old()" in str(warning) and "deprecated" in str(warning)
        for warning in result.warnings
    ), result.warnings


@pytest.mark.parametrize(
    ("code", "expected"),
    [
        # An unnamed struct named through a typedef.
        ("namespace tg { typedef struct { } Tag; }", "typedef struct tg_Tag tg_Tag;"),
        # Parameters named like a type or like a generated macro are renamed.
        ("namespace p { std::int32_t f(std::int32_t int32_t); }", "int32_t int32_t_"),
        ("namespace p { int f(int MOD_C_API_BUILD); }", "int MOD_C_API_BUILD_"),
        ("namespace p { int f(int unix, int pascal); }", "int unix_, int pascal_"),
        # Functions declared through a function type.
        ("namespace t { typedef int Op(int, int); Op add; }", "t_add(int arg1, int arg2"),
        # Final polymorphic classes are fine.
        (
            "namespace pm { class Task final { public: int run() const;"
            " private: virtual int step() const; }; }",
            "pm_Task_run(",
        ),
    ],
)
def test_accepted(tmp_path: Path, code: str, expected: str) -> None:
    assert expected in generate(tmp_path, code).files["c/api_c.h"]


def test_header_names_that_replace_package_names(tmp_path: Path) -> None:
    header = write_header(tmp_path, "namespace lb { int weight(); }", name="load.h")
    with pytest.raises(ConfigurationError, match="would replace 'load'"):
        bridgefex.generate([header], bridgefex.Options("mod"))


def test_header_names_that_differ_only_in_case(tmp_path: Path) -> None:
    first = write_header(tmp_path / "a", "namespace sa { int sides(); }", name="Shape.h")
    second = write_header(tmp_path / "b", "namespace sb { int area(); }", name="shape.h")
    with pytest.raises(GenerationError, match="same name \\(ignoring case\\)"):
        bridgefex.generate([first, second], bridgefex.Options("mod"))


@pytest.mark.parametrize("directory", ["v2*", "a\rb"])
def test_unsafe_include_paths(tmp_path: Path, directory: str) -> None:
    root = tmp_path / "include"
    header = write_header(root / directory, "namespace s { int f(); }")
    if directory == "v2*":
        # Only '*/' is unsafe; 'v2*' followed by '/api.h' makes it.
        assert "*/" in (Path(directory) / "api.h").as_posix()
    with pytest.raises(ConfigurationError, match="cannot write an #include"):
        bridgefex.generate([header], bridgefex.Options("mod", include_root=root))


@pytest.mark.parametrize("name", ["car_", "a__b"])
def test_module_names_that_make_reserved_identifiers(name: str) -> None:
    with pytest.raises(ConfigurationError, match="invalid module name"):
        bridgefex.generate([Path("x.h")], bridgefex.Options(name))
