"""Python bindings for "counter.h". Generated by bridgefex. Do not edit."""

import builtins as _builtins
import ctypes
import threading
import weakref

from . import _runtime

__all__ = [
    "Counter",
    "multiply_int32_int32",
]


class _demo_Counter(ctypes.Structure):
    """Opaque C handle of demo::Counter."""


_demo_Counter_p = ctypes.POINTER(_demo_Counter)

_lib = None
# Reentrant: a finalizer or signal handler that calls into this module can run
# while _bind() declares the signatures, in the same thread.
_bind_lock = _runtime.reset_after_fork(threading.RLock())


def _bind():
    """Load the library on first use and declare the C signatures."""
    global _lib
    if _lib is not None:
        return _lib
    # Outside the lock: load() takes a lock of its own.
    lib = _runtime.library()
    with _bind_lock:
        if _lib is None:
            lib.demo_Counter_create_void.argtypes = [ctypes.POINTER(_demo_Counter_p)]
            lib.demo_Counter_create_void.restype = _runtime.Status
            lib.demo_Counter_create_int32.argtypes = [ctypes.POINTER(_demo_Counter_p), ctypes.c_int32]
            lib.demo_Counter_create_int32.restype = _runtime.Status
            lib.demo_Counter_destroy.argtypes = [_demo_Counter_p]
            lib.demo_Counter_destroy.restype = None
            lib.demo_Counter_increment.argtypes = [_demo_Counter_p]
            lib.demo_Counter_increment.restype = _runtime.Status
            lib.demo_Counter_add_int32.argtypes = [_demo_Counter_p, ctypes.c_int32]
            lib.demo_Counter_add_int32.restype = _runtime.Status
            lib.demo_Counter_add_double.argtypes = [_demo_Counter_p, ctypes.c_double]
            lib.demo_Counter_add_double.restype = _runtime.Status
            lib.demo_Counter_value.argtypes = [_demo_Counter_p, ctypes.POINTER(ctypes.c_int32)]
            lib.demo_Counter_value.restype = _runtime.Status
            lib.demo_Counter_isZero.argtypes = [_demo_Counter_p, ctypes.POINTER(ctypes.c_bool)]
            lib.demo_Counter_isZero.restype = _runtime.Status
            lib.demo_Counter_setLimit.argtypes = [_demo_Counter_p, ctypes.c_int64]
            lib.demo_Counter_setLimit.restype = _runtime.Status
            lib.demo_Counter_limit.argtypes = [_demo_Counter_p, ctypes.POINTER(ctypes.c_int64)]
            lib.demo_Counter_limit.restype = _runtime.Status
            lib.demo_Counter_reserve.argtypes = [_demo_Counter_p, ctypes.c_size_t]
            lib.demo_Counter_reserve.restype = _runtime.Status
            lib.demo_Counter_fail.argtypes = [_demo_Counter_p]
            lib.demo_Counter_fail.restype = _runtime.Status
            lib.demo_Counter_liveInstances.argtypes = [ctypes.POINTER(ctypes.c_size_t)]
            lib.demo_Counter_liveInstances.restype = _runtime.Status
            lib.demo_multiply_int32_int32.argtypes = [ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(ctypes.c_int64)]
            lib.demo_multiply_int32_int32.restype = _runtime.Status
            _lib = lib
    return _lib


def _release(owned):
    """Destroy an object unless close() did it already: whoever pops wins."""
    try:
        handle, destroy = owned.pop()
    except IndexError:
        return
    destroy(handle)


class Counter:
    """Wraps ``demo::Counter``.

    The C++ object is destroyed by close(), at the end of a ``with`` block or
    when this object is garbage collected, whichever comes first. Objects still
    alive when the interpreter exits are not destroyed.
    """

    __slots__ = ("__weakref__", "_finalizer", "_handle", "_owned")

    def __init__(self, *args, **kwargs):
        raise _builtins.TypeError(
            "Counter has several constructors; use "
            "Counter.create_void(), Counter.create_int32()"
        )

    @_builtins.classmethod
    def create_void(cls):
        """Wraps ``demo::Counter::Counter()``."""
        _handle = _demo_Counter_p()
        _runtime.check(_bind().demo_Counter_create_void(ctypes.byref(_handle)))
        _self = cls.__new__(cls)
        _self._adopt(_handle)
        return _self

    @_builtins.classmethod
    def create_int32(cls, start):
        """Wraps ``demo::Counter::Counter(int32_t start)``."""
        _handle = _demo_Counter_p()
        _runtime.check(_bind().demo_Counter_create_int32(
            ctypes.byref(_handle),
            _runtime.to_int(start, ctypes.c_int32, "start"),
        ))
        _self = cls.__new__(cls)
        _self._adopt(_handle)
        return _self

    def _adopt(self, handle):
        if not handle:
            raise _builtins.RuntimeError(
                "demo::Counter: the C layer returned a NULL handle"
            )
        self._handle = handle
        # Shared by close() and the finalizer, so the object is destroyed once.
        self._owned = owned = [(handle, _bind().demo_Counter_destroy)]
        self._finalizer = weakref.finalize(self, _release, owned)
        # At interpreter exit, other threads may still be using the object.
        self._finalizer.atexit = False

    def _ptr(self):
        if not self._owned:
            raise _builtins.ValueError("Counter object is closed")
        return self._handle

    def close(self):
        """Destroy the C++ object now. Calling it again does nothing."""
        # Only self and builtins: in a __del__ at interpreter exit, the globals
        # of this module may be gone already, and the finalizer may have been
        # dropped without running.
        try:
            handle, destroy = self._owned.pop()
        except (AttributeError, IndexError):
            return
        self._handle = None
        self._finalizer.detach()
        destroy(handle)

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    def __copy__(self):
        raise _builtins.TypeError("Counter objects cannot be copied")

    def __deepcopy__(self, memo):
        raise _builtins.TypeError("Counter objects cannot be copied")

    def __reduce__(self):
        raise _builtins.TypeError("Counter objects cannot be pickled")

    def increment(self):
        """Wraps ``void demo::Counter::increment()``."""
        _runtime.check(_bind().demo_Counter_increment(self._ptr()))

    def add_int32(self, delta):
        """Wraps ``void demo::Counter::add(int32_t delta)``."""
        _runtime.check(_bind().demo_Counter_add_int32(
            self._ptr(),
            _runtime.to_int(delta, ctypes.c_int32, "delta"),
        ))

    def add_double(self, delta):
        """Wraps ``void demo::Counter::add(double delta)``."""
        _runtime.check(_bind().demo_Counter_add_double(
            self._ptr(),
            _runtime.to_float(delta, ctypes.c_double, "delta"),
        ))

    def value(self):
        """Wraps ``int32_t demo::Counter::value() const``."""
        _out = ctypes.c_int32()
        _runtime.check(_bind().demo_Counter_value(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def isZero(self):
        """Wraps ``bool demo::Counter::isZero() const``."""
        _out = ctypes.c_bool()
        _runtime.check(_bind().demo_Counter_isZero(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def setLimit(self, limit):
        """Wraps ``void demo::Counter::setLimit(int64_t limit)``."""
        _runtime.check(_bind().demo_Counter_setLimit(
            self._ptr(),
            _runtime.to_int(limit, ctypes.c_int64, "limit"),
        ))

    def limit(self):
        """Wraps ``int64_t demo::Counter::limit() const``."""
        _out = ctypes.c_int64()
        _runtime.check(_bind().demo_Counter_limit(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def reserve(self, bytes):
        """Wraps ``void demo::Counter::reserve(size_t bytes)``."""
        _runtime.check(_bind().demo_Counter_reserve(
            self._ptr(),
            _runtime.to_int(bytes, ctypes.c_size_t, "bytes"),
        ))

    def fail(self):
        """Wraps ``void demo::Counter::fail() const``."""
        _runtime.check(_bind().demo_Counter_fail(self._ptr()))

    @_builtins.staticmethod
    def liveInstances():
        """Wraps ``static size_t demo::Counter::liveInstances()``."""
        _out = ctypes.c_size_t()
        _runtime.check(_bind().demo_Counter_liveInstances(ctypes.byref(_out)))
        return _out.value


def multiply_int32_int32(a, b):
    """Wraps ``int64_t demo::multiply(int32_t a, int32_t b)``."""
    _out = ctypes.c_int64()
    _runtime.check(_bind().demo_multiply_int32_int32(
        _runtime.to_int(a, ctypes.c_int32, "a"),
        _runtime.to_int(b, ctypes.c_int32, "b"),
        ctypes.byref(_out),
    ))
    return _out.value
