"""Python bindings for "geometry.h". Generated by bridgefex. Do not edit."""

import builtins as _builtins
import ctypes
import threading
import weakref

from . import _runtime

__all__ = [
    "multiply_double_double",
    "Circle",
    "distance",
]


class _demo_geometry_Circle(ctypes.Structure):
    """Opaque C handle of demo::geometry::Circle."""


_demo_geometry_Circle_p = ctypes.POINTER(_demo_geometry_Circle)

_lib = None
# Reentrant: a finalizer or signal handler that calls into this module can run
# while _bind() declares the signatures, in the same thread.
_bind_lock = _runtime.reset_after_fork(threading.RLock())


def _bind():
    """Load the library on first use and declare the C signatures."""
    global _lib
    if _lib is not None:
        return _lib
    # Outside the lock: load() takes a lock of its own.
    lib = _runtime.library()
    with _bind_lock:
        if _lib is None:
            lib.demo_multiply_double_double.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.POINTER(ctypes.c_double)]
            lib.demo_multiply_double_double.restype = _runtime.Status
            lib.demo_geometry_Circle_create.argtypes = [ctypes.POINTER(_demo_geometry_Circle_p), ctypes.c_double]
            lib.demo_geometry_Circle_create.restype = _runtime.Status
            lib.demo_geometry_Circle_destroy.argtypes = [_demo_geometry_Circle_p]
            lib.demo_geometry_Circle_destroy.restype = None
            lib.demo_geometry_Circle_radius.argtypes = [_demo_geometry_Circle_p, ctypes.POINTER(ctypes.c_double)]
            lib.demo_geometry_Circle_radius.restype = _runtime.Status
            lib.demo_geometry_Circle_area.argtypes = [_demo_geometry_Circle_p, ctypes.POINTER(ctypes.c_double)]
            lib.demo_geometry_Circle_area.restype = _runtime.Status
            lib.demo_geometry_Circle_scale.argtypes = [_demo_geometry_Circle_p, ctypes.c_double]
            lib.demo_geometry_Circle_scale.restype = _runtime.Status
            lib.demo_geometry_distance.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.c_double, ctypes.POINTER(ctypes.c_double)]
            lib.demo_geometry_distance.restype = _runtime.Status
            _lib = lib
    return _lib


def _release(owned):
    """Destroy an object unless close() did it already: whoever pops wins."""
    try:
        handle, destroy = owned.pop()
    except IndexError:
        return
    destroy(handle)


def multiply_double_double(a, b):
    """Wraps ``double demo::multiply(double a, double b)``."""
    _out = ctypes.c_double()
    _runtime.check(_bind().demo_multiply_double_double(
        _runtime.to_float(a, ctypes.c_double, "a"),
        _runtime.to_float(b, ctypes.c_double, "b"),
        ctypes.byref(_out),
    ))
    return _out.value


class Circle:
    """Wraps ``demo::geometry::Circle``.

    The C++ object is destroyed by close(), at the end of a ``with`` block or
    when this object is garbage collected, whichever comes first. Objects still
    alive when the interpreter exits are not destroyed.
    """

    __slots__ = ("__weakref__", "_finalizer", "_handle", "_owned")

    def __init__(self, radius):
        """Wraps ``demo::geometry::Circle::Circle(double radius)``."""
        if _builtins.getattr(self, "_finalizer", None) is not None:
            raise _builtins.TypeError("Circle object is already initialized")
        _handle = _demo_geometry_Circle_p()
        _runtime.check(_bind().demo_geometry_Circle_create(
            ctypes.byref(_handle),
            _runtime.to_float(radius, ctypes.c_double, "radius"),
        ))
        self._adopt(_handle)

    def _adopt(self, handle):
        if not handle:
            raise _builtins.RuntimeError(
                "demo::geometry::Circle: the C layer returned a NULL handle"
            )
        self._handle = handle
        # Shared by close() and the finalizer, so the object is destroyed once.
        self._owned = owned = [(handle, _bind().demo_geometry_Circle_destroy)]
        self._finalizer = weakref.finalize(self, _release, owned)
        # At interpreter exit, other threads may still be using the object.
        self._finalizer.atexit = False

    def _ptr(self):
        if not self._owned:
            raise _builtins.ValueError("Circle object is closed")
        return self._handle

    def close(self):
        """Destroy the C++ object now. Calling it again does nothing."""
        # Only self and builtins: in a __del__ at interpreter exit, the globals
        # of this module may be gone already, and the finalizer may have been
        # dropped without running.
        try:
            handle, destroy = self._owned.pop()
        except (AttributeError, IndexError):
            return
        self._handle = None
        self._finalizer.detach()
        destroy(handle)

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    def __copy__(self):
        raise _builtins.TypeError("Circle objects cannot be copied")

    def __deepcopy__(self, memo):
        raise _builtins.TypeError("Circle objects cannot be copied")

    def __reduce__(self):
        raise _builtins.TypeError("Circle objects cannot be pickled")

    def radius(self):
        """Wraps ``double demo::geometry::Circle::radius() const``."""
        _out = ctypes.c_double()
        _runtime.check(_bind().demo_geometry_Circle_radius(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def area(self):
        """Wraps ``double demo::geometry::Circle::area() const``."""
        _out = ctypes.c_double()
        _runtime.check(_bind().demo_geometry_Circle_area(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def scale(self, factor):
        """Wraps ``void demo::geometry::Circle::scale(double factor)``."""
        _runtime.check(_bind().demo_geometry_Circle_scale(
            self._ptr(),
            _runtime.to_float(factor, ctypes.c_double, "factor"),
        ))


def distance(x1, y1, x2, y2):
    """Wraps ``double demo::geometry::distance(double x1, double y1, double x2, double y2)``."""
    _out = ctypes.c_double()
    _runtime.check(_bind().demo_geometry_distance(
        _runtime.to_float(x1, ctypes.c_double, "x1"),
        _runtime.to_float(y1, ctypes.c_double, "y1"),
        _runtime.to_float(x2, ctypes.c_double, "x2"),
        _runtime.to_float(y2, ctypes.c_double, "y2"),
        ctypes.byref(_out),
    ))
    return _out.value
