"""Runtime support for the "scalars" bindings. Generated by bridgefex. Do not edit."""

import ctypes
import functools
import math
import numbers
import operator
import os
import sys
import threading

LIBRARY_ENV_VAR = "SCALARS_LIBRARY"

API_FINGERPRINT = "3d692733d6bd514aacdf76be479829b4"
"""Fingerprint of the C API these bindings were generated for."""

Status = ctypes.c_int32

OK = 0
ERROR_EXCEPTION = 1
ERROR_UNKNOWN_EXCEPTION = 2
ERROR_NULL_ARGUMENT = 3
ERROR_OUT_OF_MEMORY = 4

_STATUS_NAMES = {
    OK: "OK",
    ERROR_EXCEPTION: "ERROR_EXCEPTION",
    ERROR_UNKNOWN_EXCEPTION: "ERROR_UNKNOWN_EXCEPTION",
    ERROR_NULL_ARGUMENT: "ERROR_NULL_ARGUMENT",
    ERROR_OUT_OF_MEMORY: "ERROR_OUT_OF_MEMORY",
}

_FLOAT_MAX = {ctypes.c_float: 3.4028234663852886e38}


class Error(Exception):
    """A call into the C++ library failed.

    ``status`` is one of the ERROR_* codes and ``message`` the text reported
    by the C++ code (for exceptions, their ``what()``).
    """

    def __init__(self, status, message):
        super().__init__(message)
        self.status = status
        self.message = message

    @property
    def status_name(self):
        return _STATUS_NAMES.get(self.status, f"UNKNOWN_STATUS_{self.status}")

    def __reduce__(self):
        # Errors can then be pickled, e.g. to come back from a worker process.
        return (type(self), (self.status, self.message))


# Reentrant: a finalizer or signal handler that calls into the bindings can run
# while the library is being loaded, in the same thread.
_lock = threading.RLock()
_library = None
_library_path = None
"""Absolute path of the loaded library, or its bare file name when the system
search path was used."""


def _has_directory(path):
    return os.sep in path or (os.altsep is not None and os.altsep in path)


def _is_loaded_from(path):
    if _has_directory(path) and _has_directory(_library_path):
        return os.path.realpath(path) == os.path.realpath(_library_path)
    return path == _library_path


def _default_library_name():
    if sys.platform == "win32":
        return "scalars.dll"
    if sys.platform == "darwin":
        return "libscalars.dylib"
    return "libscalars.so"


def load(path=None):
    """Load the shared library that contains the "scalars" C API.

    The library is taken from ``path``, else from the SCALARS_LIBRARY
    environment variable, else from a file named like the platform's shared
    libraries (libscalars.so, scalars.dll, libscalars.dylib) next to this
    package, else from the system search path. Importing the modules of this
    package does not load anything: the first call does, with these rules,
    unless load() was called before. Returns the ctypes library object.
    """
    global _library, _library_path
    with _lock:
        path = os.fsdecode(path) if path is not None else None
        if _library is not None:
            if path and not _is_loaded_from(path):
                raise RuntimeError(
                    f"the scalars library is already loaded from {_library_path!r}"
                )
            return _library
        if not path:
            path = os.environ.get(LIBRARY_ENV_VAR) or None
        if path is None:
            name = _default_library_name()
            bundled = os.path.join(os.path.dirname(os.path.abspath(__file__)), name)
            path = bundled if os.path.isfile(bundled) else name
        try:
            library = ctypes.CDLL(path)
        except OSError as error:
            raise OSError(
                f"cannot load the scalars library from {path!r} ({error}); "
                f"call scalars.load(path) or set {LIBRARY_ENV_VAR}"
            ) from error
        _check_fingerprint(library, path)
        library.scalars_last_error.argtypes = []
        library.scalars_last_error.restype = ctypes.c_char_p
        library_path = os.path.abspath(path) if _has_directory(path) else path
        if _library is None:  # else a reentrant call loaded it in the meantime
            _library, _library_path = library, library_path
        return _library


def _check_fingerprint(library, path):
    """Refuse a library built from a different version of the generated C API."""
    try:
        get_fingerprint = library.scalars_api_fingerprint
    except AttributeError:
        found = None
    else:
        get_fingerprint.argtypes = []
        get_fingerprint.restype = ctypes.c_char_p
        found = get_fingerprint().decode("ascii", "replace")
    if found != API_FINGERPRINT:
        raise RuntimeError(
            f"{path!r} does not match these bindings (C API fingerprint {found!r}, "
            f"expected {API_FINGERPRINT!r}); rebuild the library from the same "
            "bridgefex output"
        )


def library():
    """The loaded library, loading it with the default rules if needed."""
    return load()


def check(status):
    """Raise Error if a call did not return OK."""
    if status != OK:
        message = _library.scalars_last_error()
        raise Error(status, message.decode("utf-8", "replace") if message else "")


@functools.cache
def _integer_range(ctype):
    bits = 8 * ctypes.sizeof(ctype)
    if ctype(-1).value < 0:
        return -(1 << (bits - 1)), (1 << (bits - 1)) - 1
    return 0, (1 << bits) - 1


def to_int(value, ctype, name):
    """Check that value fits in the C integer type; ctypes would silently wrap it."""
    if isinstance(value, bool):
        raise TypeError(f"argument {name!r} must be an integer, not bool")
    try:
        number = operator.index(value)
    except TypeError:
        raise TypeError(
            f"argument {name!r} must be an integer, not {type(value).__name__}"
        ) from None
    low, high = _integer_range(ctype)
    if not low <= number <= high:
        raise OverflowError(f"argument {name!r} must be in [{low}, {high}], got {number}")
    return number


def to_bool(value, name):
    """Accept only True and False, so that mistakes such as passing 2 are caught."""
    if not isinstance(value, bool):
        raise TypeError(f"argument {name!r} must be a bool, not {type(value).__name__}")
    return value


def to_float(value, ctype, name):
    """Check that value is a real number that fits in the C floating type."""
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        raise TypeError(f"argument {name!r} must be a real number, not {type(value).__name__}")
    number = float(value)
    limit = _FLOAT_MAX.get(ctype)
    if limit is not None and math.isfinite(number) and abs(number) > limit:
        raise OverflowError(f"argument {name!r} must be in [{-limit}, {limit}], got {number}")
    return number
