"""Python bindings for "numbers.h". Generated by bridgefex. Do not edit."""

import builtins as _builtins
import ctypes
import threading
import weakref

from . import _runtime

__all__ = [
    "Accumulator",
    "echo_bool",
    "echo_schar",
    "echo_uchar",
    "echo_short",
    "echo_ushort",
    "echo_int",
    "echo_uint",
    "echo_long",
    "echo_ulong",
    "echo_llong",
    "echo_ullong",
    "echo_float",
    "echo_double",
    "echo_int8",
    "echo_int16",
    "echo_int32",
    "echo_int64",
    "echo_uint8",
    "echo_uint16",
    "echo_uint32",
    "echo_uint64",
    "echo_size",
    "echo_const",
    "sum_renamed",
    "twice",
    "scale_double",
    "scale_double_double",
    "divide",
    "do_nothing",
]


class _scalars_Accumulator(ctypes.Structure):
    """Opaque C handle of Accumulator."""


_scalars_Accumulator_p = ctypes.POINTER(_scalars_Accumulator)

_lib = None
_bind_lock = threading.Lock()


def _bind():
    """Load the library on first use and declare the C signatures."""
    global _lib
    if _lib is not None:
        return _lib
    # Outside the lock: load() takes a lock of its own.
    lib = _runtime.library()
    with _bind_lock:
        if _lib is None:
            lib.scalars_Accumulator_create.argtypes = [ctypes.POINTER(_scalars_Accumulator_p)]
            lib.scalars_Accumulator_create.restype = _runtime.Status
            lib.scalars_Accumulator_destroy.argtypes = [_scalars_Accumulator_p]
            lib.scalars_Accumulator_destroy.restype = None
            lib.scalars_Accumulator_push.argtypes = [_scalars_Accumulator_p, ctypes.c_double]
            lib.scalars_Accumulator_push.restype = _runtime.Status
            lib.scalars_Accumulator_total.argtypes = [_scalars_Accumulator_p, ctypes.POINTER(ctypes.c_double)]
            lib.scalars_Accumulator_total.restype = _runtime.Status
            lib.scalars_Accumulator_count.argtypes = [_scalars_Accumulator_p, ctypes.POINTER(ctypes.c_size_t)]
            lib.scalars_Accumulator_count.restype = _runtime.Status
            lib.scalars_Accumulator_reset.argtypes = [_scalars_Accumulator_p]
            lib.scalars_Accumulator_reset.restype = _runtime.Status
            lib.scalars_Accumulator_version.argtypes = [ctypes.POINTER(ctypes.c_int)]
            lib.scalars_Accumulator_version.restype = _runtime.Status
            lib.scalars_echo_bool.argtypes = [ctypes.c_bool, ctypes.POINTER(ctypes.c_bool)]
            lib.scalars_echo_bool.restype = _runtime.Status
            lib.scalars_echo_schar.argtypes = [ctypes.c_byte, ctypes.POINTER(ctypes.c_byte)]
            lib.scalars_echo_schar.restype = _runtime.Status
            lib.scalars_echo_uchar.argtypes = [ctypes.c_ubyte, ctypes.POINTER(ctypes.c_ubyte)]
            lib.scalars_echo_uchar.restype = _runtime.Status
            lib.scalars_echo_short.argtypes = [ctypes.c_short, ctypes.POINTER(ctypes.c_short)]
            lib.scalars_echo_short.restype = _runtime.Status
            lib.scalars_echo_ushort.argtypes = [ctypes.c_ushort, ctypes.POINTER(ctypes.c_ushort)]
            lib.scalars_echo_ushort.restype = _runtime.Status
            lib.scalars_echo_int.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.scalars_echo_int.restype = _runtime.Status
            lib.scalars_echo_uint.argtypes = [ctypes.c_uint, ctypes.POINTER(ctypes.c_uint)]
            lib.scalars_echo_uint.restype = _runtime.Status
            lib.scalars_echo_long.argtypes = [ctypes.c_long, ctypes.POINTER(ctypes.c_long)]
            lib.scalars_echo_long.restype = _runtime.Status
            lib.scalars_echo_ulong.argtypes = [ctypes.c_ulong, ctypes.POINTER(ctypes.c_ulong)]
            lib.scalars_echo_ulong.restype = _runtime.Status
            lib.scalars_echo_llong.argtypes = [ctypes.c_longlong, ctypes.POINTER(ctypes.c_longlong)]
            lib.scalars_echo_llong.restype = _runtime.Status
            lib.scalars_echo_ullong.argtypes = [ctypes.c_ulonglong, ctypes.POINTER(ctypes.c_ulonglong)]
            lib.scalars_echo_ullong.restype = _runtime.Status
            lib.scalars_echo_float.argtypes = [ctypes.c_float, ctypes.POINTER(ctypes.c_float)]
            lib.scalars_echo_float.restype = _runtime.Status
            lib.scalars_echo_double.argtypes = [ctypes.c_double, ctypes.POINTER(ctypes.c_double)]
            lib.scalars_echo_double.restype = _runtime.Status
            lib.scalars_echo_int8.argtypes = [ctypes.c_int8, ctypes.POINTER(ctypes.c_int8)]
            lib.scalars_echo_int8.restype = _runtime.Status
            lib.scalars_echo_int16.argtypes = [ctypes.c_int16, ctypes.POINTER(ctypes.c_int16)]
            lib.scalars_echo_int16.restype = _runtime.Status
            lib.scalars_echo_int32.argtypes = [ctypes.c_int32, ctypes.POINTER(ctypes.c_int32)]
            lib.scalars_echo_int32.restype = _runtime.Status
            lib.scalars_echo_int64.argtypes = [ctypes.c_int64, ctypes.POINTER(ctypes.c_int64)]
            lib.scalars_echo_int64.restype = _runtime.Status
            lib.scalars_echo_uint8.argtypes = [ctypes.c_uint8, ctypes.POINTER(ctypes.c_uint8)]
            lib.scalars_echo_uint8.restype = _runtime.Status
            lib.scalars_echo_uint16.argtypes = [ctypes.c_uint16, ctypes.POINTER(ctypes.c_uint16)]
            lib.scalars_echo_uint16.restype = _runtime.Status
            lib.scalars_echo_uint32.argtypes = [ctypes.c_uint32, ctypes.POINTER(ctypes.c_uint32)]
            lib.scalars_echo_uint32.restype = _runtime.Status
            lib.scalars_echo_uint64.argtypes = [ctypes.c_uint64, ctypes.POINTER(ctypes.c_uint64)]
            lib.scalars_echo_uint64.restype = _runtime.Status
            lib.scalars_echo_size.argtypes = [ctypes.c_size_t, ctypes.POINTER(ctypes.c_size_t)]
            lib.scalars_echo_size.restype = _runtime.Status
            lib.scalars_echo_const.argtypes = [ctypes.c_int32, ctypes.POINTER(ctypes.c_int32)]
            lib.scalars_echo_const.restype = _runtime.Status
            lib.scalars_sum_renamed.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.scalars_sum_renamed.restype = _runtime.Status
            lib.scalars_twice.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.scalars_twice.restype = _runtime.Status
            lib.scalars_scale_double.argtypes = [ctypes.c_double, ctypes.POINTER(ctypes.c_double)]
            lib.scalars_scale_double.restype = _runtime.Status
            lib.scalars_scale_double_double.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.POINTER(ctypes.c_double)]
            lib.scalars_scale_double_double.restype = _runtime.Status
            lib.scalars_divide.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.scalars_divide.restype = _runtime.Status
            lib.scalars_do_nothing.argtypes = []
            lib.scalars_do_nothing.restype = _runtime.Status
            _lib = lib
    return _lib


class Accumulator:
    """Wraps ``Accumulator``.

    The C++ object is destroyed by close(), at the end of a ``with`` block or
    when this object is garbage collected, whichever comes first. Objects still
    alive when the interpreter exits are not destroyed.
    """

    __slots__ = ("__weakref__", "_finalizer", "_handle")

    def __init__(self):
        """Wraps ``Accumulator::Accumulator()``."""
        if _builtins.getattr(self, "_finalizer", None) is not None:
            raise _builtins.TypeError("Accumulator object is already initialized")
        _handle = _scalars_Accumulator_p()
        _runtime.check(_bind().scalars_Accumulator_create(ctypes.byref(_handle)))
        self._adopt(_handle)

    def _adopt(self, handle):
        if not handle:
            raise _builtins.RuntimeError(
                "Accumulator: the C layer returned a NULL handle"
            )
        self._handle = handle
        self._finalizer = weakref.finalize(self, _bind().scalars_Accumulator_destroy, handle)
        # At interpreter exit, other threads may still be using the object.
        self._finalizer.atexit = False

    def _ptr(self):
        if not self._finalizer.alive:
            raise _builtins.ValueError("Accumulator object is closed")
        return self._handle

    def close(self):
        """Destroy the C++ object now. Calling it again does nothing."""
        finalizer = _builtins.getattr(self, "_finalizer", None)
        # detach() also works during interpreter shutdown, unlike calling the finalizer.
        pending = finalizer.detach() if finalizer is not None else None
        if pending is not None:
            _, destroy, arguments, _ = pending
            destroy(*arguments)

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    def __copy__(self):
        raise _builtins.TypeError("Accumulator objects cannot be copied")

    def __deepcopy__(self, memo):
        raise _builtins.TypeError("Accumulator objects cannot be copied")

    def __reduce__(self):
        raise _builtins.TypeError("Accumulator objects cannot be pickled")

    def push(self, value):
        """Wraps ``void Accumulator::push(double value)``."""
        _runtime.check(_bind().scalars_Accumulator_push(
            self._ptr(),
            _runtime.to_float(value, ctypes.c_double, "value"),
        ))

    def total(self):
        """Wraps ``double Accumulator::total() const``."""
        _out = ctypes.c_double()
        _runtime.check(_bind().scalars_Accumulator_total(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def count(self):
        """Wraps ``size_t Accumulator::count() const``."""
        _out = ctypes.c_size_t()
        _runtime.check(_bind().scalars_Accumulator_count(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def reset(self):
        """Wraps ``void Accumulator::reset()``."""
        _runtime.check(_bind().scalars_Accumulator_reset(self._ptr()))

    @_builtins.staticmethod
    def version():
        """Wraps ``static int Accumulator::version()``."""
        _out = ctypes.c_int()
        _runtime.check(_bind().scalars_Accumulator_version(ctypes.byref(_out)))
        return _out.value


def echo_bool(value):
    """Wraps ``bool echo_bool(bool value)``."""
    _out = ctypes.c_bool()
    _runtime.check(_bind().scalars_echo_bool(_runtime.to_bool(value, "value"), ctypes.byref(_out)))
    return _out.value


def echo_schar(value):
    """Wraps ``signed char echo_schar(signed char value)``."""
    _out = ctypes.c_byte()
    _runtime.check(_bind().scalars_echo_schar(
        _runtime.to_int(value, ctypes.c_byte, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uchar(value):
    """Wraps ``unsigned char echo_uchar(unsigned char value)``."""
    _out = ctypes.c_ubyte()
    _runtime.check(_bind().scalars_echo_uchar(
        _runtime.to_int(value, ctypes.c_ubyte, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_short(value):
    """Wraps ``short echo_short(short value)``."""
    _out = ctypes.c_short()
    _runtime.check(_bind().scalars_echo_short(
        _runtime.to_int(value, ctypes.c_short, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_ushort(value):
    """Wraps ``unsigned short echo_ushort(unsigned short value)``."""
    _out = ctypes.c_ushort()
    _runtime.check(_bind().scalars_echo_ushort(
        _runtime.to_int(value, ctypes.c_ushort, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_int(value):
    """Wraps ``int echo_int(int value)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().scalars_echo_int(
        _runtime.to_int(value, ctypes.c_int, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uint(value):
    """Wraps ``unsigned int echo_uint(unsigned int value)``."""
    _out = ctypes.c_uint()
    _runtime.check(_bind().scalars_echo_uint(
        _runtime.to_int(value, ctypes.c_uint, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_long(value):
    """Wraps ``long echo_long(long value)``."""
    _out = ctypes.c_long()
    _runtime.check(_bind().scalars_echo_long(
        _runtime.to_int(value, ctypes.c_long, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_ulong(value):
    """Wraps ``unsigned long echo_ulong(unsigned long value)``."""
    _out = ctypes.c_ulong()
    _runtime.check(_bind().scalars_echo_ulong(
        _runtime.to_int(value, ctypes.c_ulong, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_llong(value):
    """Wraps ``long long echo_llong(long long value)``."""
    _out = ctypes.c_longlong()
    _runtime.check(_bind().scalars_echo_llong(
        _runtime.to_int(value, ctypes.c_longlong, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_ullong(value):
    """Wraps ``unsigned long long echo_ullong(unsigned long long value)``."""
    _out = ctypes.c_ulonglong()
    _runtime.check(_bind().scalars_echo_ullong(
        _runtime.to_int(value, ctypes.c_ulonglong, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_float(value):
    """Wraps ``float echo_float(float value)``."""
    _out = ctypes.c_float()
    _runtime.check(_bind().scalars_echo_float(
        _runtime.to_float(value, ctypes.c_float, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_double(value):
    """Wraps ``double echo_double(double value)``."""
    _out = ctypes.c_double()
    _runtime.check(_bind().scalars_echo_double(
        _runtime.to_float(value, ctypes.c_double, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_int8(value):
    """Wraps ``int8_t echo_int8(int8_t value)``."""
    _out = ctypes.c_int8()
    _runtime.check(_bind().scalars_echo_int8(
        _runtime.to_int(value, ctypes.c_int8, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_int16(value):
    """Wraps ``int16_t echo_int16(int16_t value)``."""
    _out = ctypes.c_int16()
    _runtime.check(_bind().scalars_echo_int16(
        _runtime.to_int(value, ctypes.c_int16, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_int32(value):
    """Wraps ``int32_t echo_int32(int32_t value)``."""
    _out = ctypes.c_int32()
    _runtime.check(_bind().scalars_echo_int32(
        _runtime.to_int(value, ctypes.c_int32, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_int64(value):
    """Wraps ``int64_t echo_int64(int64_t value)``."""
    _out = ctypes.c_int64()
    _runtime.check(_bind().scalars_echo_int64(
        _runtime.to_int(value, ctypes.c_int64, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uint8(value):
    """Wraps ``uint8_t echo_uint8(uint8_t value)``."""
    _out = ctypes.c_uint8()
    _runtime.check(_bind().scalars_echo_uint8(
        _runtime.to_int(value, ctypes.c_uint8, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uint16(value):
    """Wraps ``uint16_t echo_uint16(uint16_t value)``."""
    _out = ctypes.c_uint16()
    _runtime.check(_bind().scalars_echo_uint16(
        _runtime.to_int(value, ctypes.c_uint16, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uint32(value):
    """Wraps ``uint32_t echo_uint32(uint32_t value)``."""
    _out = ctypes.c_uint32()
    _runtime.check(_bind().scalars_echo_uint32(
        _runtime.to_int(value, ctypes.c_uint32, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_uint64(value):
    """Wraps ``uint64_t echo_uint64(uint64_t value)``."""
    _out = ctypes.c_uint64()
    _runtime.check(_bind().scalars_echo_uint64(
        _runtime.to_int(value, ctypes.c_uint64, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_size(value):
    """Wraps ``size_t echo_size(size_t value)``."""
    _out = ctypes.c_size_t()
    _runtime.check(_bind().scalars_echo_size(
        _runtime.to_int(value, ctypes.c_size_t, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def echo_const(value):
    """Wraps ``int32_t echo_const(int32_t value)``."""
    _out = ctypes.c_int32()
    _runtime.check(_bind().scalars_echo_const(
        _runtime.to_int(value, ctypes.c_int32, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def sum_renamed(lambda_, self_, restrict_, out_result_):
    """Wraps ``int sum_renamed(int lambda, int self, int restrict, int out_result)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().scalars_sum_renamed(
        _runtime.to_int(lambda_, ctypes.c_int, "lambda_"),
        _runtime.to_int(self_, ctypes.c_int, "self_"),
        _runtime.to_int(restrict_, ctypes.c_int, "restrict_"),
        _runtime.to_int(out_result_, ctypes.c_int, "out_result_"),
        ctypes.byref(_out),
    ))
    return _out.value


def twice(arg1):
    """Wraps ``int twice(int)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().scalars_twice(
        _runtime.to_int(arg1, ctypes.c_int, "arg1"),
        ctypes.byref(_out),
    ))
    return _out.value


def scale_double(value):
    """Wraps ``double scale(double value)``."""
    _out = ctypes.c_double()
    _runtime.check(_bind().scalars_scale_double(
        _runtime.to_float(value, ctypes.c_double, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def scale_double_double(value, factor):
    """Wraps ``double scale(double value, double factor)``."""
    _out = ctypes.c_double()
    _runtime.check(_bind().scalars_scale_double_double(
        _runtime.to_float(value, ctypes.c_double, "value"),
        _runtime.to_float(factor, ctypes.c_double, "factor"),
        ctypes.byref(_out),
    ))
    return _out.value


def divide(dividend, divisor):
    """Wraps ``int divide(int dividend, int divisor)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().scalars_divide(
        _runtime.to_int(dividend, ctypes.c_int, "dividend"),
        _runtime.to_int(divisor, ctypes.c_int, "divisor"),
        ctypes.byref(_out),
    ))
    return _out.value


def do_nothing():
    """Wraps ``void do_nothing()``."""
    _runtime.check(_bind().scalars_do_nothing())
