// Generated by bridgefex from "numbers.h". Do not edit.
#ifndef SCALARS_C_API_BUILD
#define SCALARS_C_API_BUILD
#endif

// The standard headers that the generated code needs come before the wrapped
// header, so that its macros cannot change them.
#include <cstddef>
#include <exception>
#include <new>
#if defined(__GLIBCXX__)
#include <bits/cxxabi_forced.h>
#endif

// The wrapped header comes before the generated ones: a global C++ declaration
// that clashed with a generated C function would then be a compile error, not a
// silent redirection.
#include "numbers.h"

#include "numbers_c.h"
#include "scalars_runtime_internal.hpp"

#if !defined(__cpp_aligned_new)
// Before C++17, new ignores alignments larger than the default one of the
// platform's operator new.
namespace scalars_detail {
#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
constexpr std::size_t new_alignment = __STDCPP_DEFAULT_NEW_ALIGNMENT__;
#elif defined(_MSC_VER) && defined(_WIN64)
constexpr std::size_t new_alignment = 16;  // std::max_align_t is double there
#else
constexpr std::size_t new_alignment = alignof(std::max_align_t);
#endif
}  // namespace scalars_detail
static_assert(alignof(::Accumulator) <= scalars_detail::new_alignment,
              "Accumulator is over-aligned: compile this file as C++17 or later");
#endif

extern "C" {

// Accumulator::Accumulator()
scalars_status scalars_Accumulator_create(scalars_Accumulator** out_self)
{
    if (out_self == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_create: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return scalars_detail::guard([&]() { *out_self = reinterpret_cast<scalars_Accumulator*>(new ::Accumulator()); });
}

// Accumulator::~Accumulator()
void scalars_Accumulator_destroy(scalars_Accumulator* self)
{
    // A destructor that throws cannot report it here, and last_error is left
    // alone because a failed call may not have been inspected yet.
    scalars_detail::guard_silently([&]() { delete reinterpret_cast<::Accumulator*>(self); });
}

// void Accumulator::push(double value)
scalars_status scalars_Accumulator_push(scalars_Accumulator* self, double value)
{
    if (self == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_push: 'self' is NULL");
    }
    return scalars_detail::guard([&]() { reinterpret_cast<::Accumulator*>(self)->push(value); });
}

// double Accumulator::total() const
scalars_status scalars_Accumulator_total(const scalars_Accumulator* self, double* out_result)
{
    if (self == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_total: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_total: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = reinterpret_cast<const ::Accumulator*>(self)->total(); });
}

// size_t Accumulator::count() const
scalars_status scalars_Accumulator_count(const scalars_Accumulator* self, size_t* out_result)
{
    if (self == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_count: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_count: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = reinterpret_cast<const ::Accumulator*>(self)->count(); });
}

// void Accumulator::reset()
scalars_status scalars_Accumulator_reset(scalars_Accumulator* self)
{
    if (self == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_reset: 'self' is NULL");
    }
    return scalars_detail::guard([&]() { reinterpret_cast<::Accumulator*>(self)->reset(); });
}

// static int Accumulator::version()
scalars_status scalars_Accumulator_version(int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_Accumulator_version: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::Accumulator::version(); });
}

// bool echo_bool(bool value)
scalars_status scalars_echo_bool(bool value, bool* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_bool: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_bool(value); });
}

// signed char echo_schar(signed char value)
scalars_status scalars_echo_schar(signed char value, signed char* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_schar: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_schar(value); });
}

// unsigned char echo_uchar(unsigned char value)
scalars_status scalars_echo_uchar(unsigned char value, unsigned char* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uchar: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uchar(value); });
}

// short echo_short(short value)
scalars_status scalars_echo_short(short value, short* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_short: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_short(value); });
}

// unsigned short echo_ushort(unsigned short value)
scalars_status scalars_echo_ushort(unsigned short value, unsigned short* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_ushort: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_ushort(value); });
}

// int echo_int(int value)
scalars_status scalars_echo_int(int value, int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_int: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_int(value); });
}

// unsigned int echo_uint(unsigned int value)
scalars_status scalars_echo_uint(unsigned int value, unsigned int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uint: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uint(value); });
}

// long echo_long(long value)
scalars_status scalars_echo_long(long value, long* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_long: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_long(value); });
}

// unsigned long echo_ulong(unsigned long value)
scalars_status scalars_echo_ulong(unsigned long value, unsigned long* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_ulong: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_ulong(value); });
}

// long long echo_llong(long long value)
scalars_status scalars_echo_llong(long long value, long long* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_llong: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_llong(value); });
}

// unsigned long long echo_ullong(unsigned long long value)
scalars_status scalars_echo_ullong(unsigned long long value, unsigned long long* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_ullong: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_ullong(value); });
}

// float echo_float(float value)
scalars_status scalars_echo_float(float value, float* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_float: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_float(value); });
}

// double echo_double(double value)
scalars_status scalars_echo_double(double value, double* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_double: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_double(value); });
}

// int8_t echo_int8(int8_t value)
scalars_status scalars_echo_int8(int8_t value, int8_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_int8: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_int8(value); });
}

// int16_t echo_int16(int16_t value)
scalars_status scalars_echo_int16(int16_t value, int16_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_int16: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_int16(value); });
}

// int32_t echo_int32(int32_t value)
scalars_status scalars_echo_int32(int32_t value, int32_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_int32: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_int32(value); });
}

// int64_t echo_int64(int64_t value)
scalars_status scalars_echo_int64(int64_t value, int64_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_int64: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_int64(value); });
}

// uint8_t echo_uint8(uint8_t value)
scalars_status scalars_echo_uint8(uint8_t value, uint8_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uint8: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uint8(value); });
}

// uint16_t echo_uint16(uint16_t value)
scalars_status scalars_echo_uint16(uint16_t value, uint16_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uint16: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uint16(value); });
}

// uint32_t echo_uint32(uint32_t value)
scalars_status scalars_echo_uint32(uint32_t value, uint32_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uint32: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uint32(value); });
}

// uint64_t echo_uint64(uint64_t value)
scalars_status scalars_echo_uint64(uint64_t value, uint64_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_uint64: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_uint64(value); });
}

// size_t echo_size(size_t value)
scalars_status scalars_echo_size(size_t value, size_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_size: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_size(value); });
}

// int32_t echo_const(int32_t value)
scalars_status scalars_echo_const(int32_t value, int32_t* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_echo_const: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::echo_const(value); });
}

// int sum_renamed(int lambda, int self, int restrict, int out_result)
scalars_status scalars_sum_renamed(int lambda_, int self_, int restrict_, int out_result_, int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_sum_renamed: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::sum_renamed(lambda_, self_, restrict_, out_result_); });
}

// int twice(int)
scalars_status scalars_twice(int arg1, int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_twice: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::twice(arg1); });
}

// double scale(double value)
scalars_status scalars_scale_double(double value, double* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_scale_double: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::scale(value); });
}

// double scale(double value, double factor)
scalars_status scalars_scale_double_double(double value, double factor, double* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_scale_double_double: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::scale(value, factor); });
}

// int divide(int dividend, int divisor)
scalars_status scalars_divide(int dividend, int divisor, int* out_result)
{
    if (out_result == nullptr) {
        return scalars_detail::null_argument("scalars_divide: 'out_result' is NULL");
    }
    return scalars_detail::guard([&]() { *out_result = ::divide(dividend, divisor); });
}

// void do_nothing()
scalars_status scalars_do_nothing(void)
{
    return scalars_detail::guard([&]() { ::do_nothing(); });
}

}  // extern "C"
