/* Generated by bridgefex from "numbers.h". Do not edit. */
#ifndef SCALARS_NUMBERS_C_H
#define SCALARS_NUMBERS_C_H

#include "scalars_runtime.h"

/* Opaque handles. In C++ they are the wrapped classes themselves. */
#ifdef __cplusplus
struct Accumulator;
typedef ::Accumulator scalars_Accumulator;
#else
typedef struct scalars_Accumulator scalars_Accumulator;
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Accumulator::Accumulator() */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_create(scalars_Accumulator** out_self);

/* Accumulator::~Accumulator() */
SCALARS_API void scalars_Accumulator_destroy(scalars_Accumulator* self);

/* void Accumulator::push(double value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_push(scalars_Accumulator* self, double value);

/* double Accumulator::total() const */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_total(const scalars_Accumulator* self, double* out_result);

/* size_t Accumulator::count() const */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_count(const scalars_Accumulator* self, size_t* out_result);

/* void Accumulator::reset() */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_reset(scalars_Accumulator* self);

/* static int Accumulator::version() */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_Accumulator_version(int* out_result);

/* bool echo_bool(bool value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_bool(bool value, bool* out_result);

/* signed char echo_schar(signed char value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_schar(signed char value, signed char* out_result);

/* unsigned char echo_uchar(unsigned char value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uchar(unsigned char value, unsigned char* out_result);

/* short echo_short(short value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_short(short value, short* out_result);

/* unsigned short echo_ushort(unsigned short value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_ushort(unsigned short value, unsigned short* out_result);

/* int echo_int(int value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_int(int value, int* out_result);

/* unsigned int echo_uint(unsigned int value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uint(unsigned int value, unsigned int* out_result);

/* long echo_long(long value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_long(long value, long* out_result);

/* unsigned long echo_ulong(unsigned long value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_ulong(unsigned long value, unsigned long* out_result);

/* long long echo_llong(long long value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_llong(long long value, long long* out_result);

/* unsigned long long echo_ullong(unsigned long long value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_ullong(unsigned long long value, unsigned long long* out_result);

/* float echo_float(float value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_float(float value, float* out_result);

/* double echo_double(double value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_double(double value, double* out_result);

/* int8_t echo_int8(int8_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_int8(int8_t value, int8_t* out_result);

/* int16_t echo_int16(int16_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_int16(int16_t value, int16_t* out_result);

/* int32_t echo_int32(int32_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_int32(int32_t value, int32_t* out_result);

/* int64_t echo_int64(int64_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_int64(int64_t value, int64_t* out_result);

/* uint8_t echo_uint8(uint8_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uint8(uint8_t value, uint8_t* out_result);

/* uint16_t echo_uint16(uint16_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uint16(uint16_t value, uint16_t* out_result);

/* uint32_t echo_uint32(uint32_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uint32(uint32_t value, uint32_t* out_result);

/* uint64_t echo_uint64(uint64_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_uint64(uint64_t value, uint64_t* out_result);

/* size_t echo_size(size_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_size(size_t value, size_t* out_result);

/* int32_t echo_const(int32_t value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_echo_const(int32_t value, int32_t* out_result);

/* int sum_renamed(int lambda, int self, int restrict, int out_result) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_sum_renamed(int lambda_, int self_, int restrict_, int out_result_, int* out_result);

/* int twice(int) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_twice(int arg1, int* out_result);

/* double scale(double value) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_scale_double(double value, double* out_result);

/* double scale(double value, double factor) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_scale_double_double(double value, double factor, double* out_result);

/* int divide(int dividend, int divisor) */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_divide(int dividend, int divisor, int* out_result);

/* void do_nothing() */
SCALARS_NODISCARD SCALARS_API scalars_status scalars_do_nothing(void);

#ifdef __cplusplus
}
#endif

#endif /* SCALARS_NUMBERS_C_H */
