// Generated by bridgefex. Do not edit.
// Helpers for the generated C++ sources of the "scalars" C API. Not part of
// the public API.
#ifndef SCALARS_RUNTIME_INTERNAL_HPP
#define SCALARS_RUNTIME_INTERNAL_HPP

#include "scalars_runtime.h"

#include <exception>
#include <new>

namespace scalars_detail {

// Stores a copy of message as the last error of the calling thread.
void set_last_error(const char* message) noexcept;

inline scalars_status null_argument(const char* message) noexcept
{
    set_last_error(message);
    return SCALARS_ERROR_NULL_ARGUMENT;
}

// Runs function and turns any exception into a status code, so that no
// exception crosses the C boundary.
template <typename Function>
scalars_status guard(const Function& function) noexcept
{
    try {
        function();
        return SCALARS_OK;
    } catch (const std::bad_alloc& error) {
        set_last_error(error.what());
        return SCALARS_ERROR_OUT_OF_MEMORY;
    } catch (const std::exception& error) {
        set_last_error(error.what());
        return SCALARS_ERROR_EXCEPTION;
    } catch (...) {
        set_last_error("unknown C++ exception");
        return SCALARS_ERROR_UNKNOWN_EXCEPTION;
    }
}

}  // namespace scalars_detail

#endif  // SCALARS_RUNTIME_INTERNAL_HPP
