"""Python bindings for the "edge" C API. Generated by bridgefex. Do not edit.

Each header has its own module (edge.edge).
The shared library is loaded on the first call; to choose it explicitly, call
load(path) before that.
"""

from ._runtime import (
    ERROR_EXCEPTION,
    ERROR_NULL_ARGUMENT,
    ERROR_OUT_OF_MEMORY,
    ERROR_UNKNOWN_EXCEPTION,
    OK,
    Error,
    load,
)

__all__ = [
    "ERROR_EXCEPTION",
    "ERROR_NULL_ARGUMENT",
    "ERROR_OUT_OF_MEMORY",
    "ERROR_UNKNOWN_EXCEPTION",
    "OK",
    "Error",
    "load",
]
