"""Python bindings for "edge.h". Generated by bridgefex. Do not edit."""

import builtins as _builtins
import ctypes
import threading
import weakref

from . import _runtime

__all__ = [
    "add",
    "combine",
    "getattr",
    "threading_",
    "Registry",
]


class _edge_Registry(ctypes.Structure):
    """Opaque C handle of edge::Registry."""


_edge_Registry_p = ctypes.POINTER(_edge_Registry)

_lib = None
_bind_lock = threading.Lock()


def _bind():
    """Load the library on first use and declare the C signatures."""
    global _lib
    if _lib is not None:
        return _lib
    # Outside the lock: load() takes a lock of its own.
    lib = _runtime.library()
    with _bind_lock:
        if _lib is None:
            lib.edge_add.argtypes = [ctypes.c_int, ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.edge_add.restype = _runtime.Status
            lib.edge_combine.argtypes = [ctypes.c_int32, ctypes.c_size_t, ctypes.c_int, ctypes.POINTER(ctypes.c_int64)]
            lib.edge_combine.restype = _runtime.Status
            lib.edge_getattr.argtypes = [ctypes.c_int, ctypes.POINTER(ctypes.c_int)]
            lib.edge_getattr.restype = _runtime.Status
            lib.edge_threading.argtypes = [ctypes.POINTER(ctypes.c_int)]
            lib.edge_threading.restype = _runtime.Status
            lib.edge_Registry_create.argtypes = [ctypes.POINTER(_edge_Registry_p)]
            lib.edge_Registry_create.restype = _runtime.Status
            lib.edge_Registry_destroy.argtypes = [_edge_Registry_p]
            lib.edge_Registry_destroy.restype = None
            lib.edge_Registry_classmethod.argtypes = [_edge_Registry_p, ctypes.POINTER(ctypes.c_int)]
            lib.edge_Registry_classmethod.restype = _runtime.Status
            lib.edge_Registry_staticmethod.argtypes = [_edge_Registry_p, ctypes.POINTER(ctypes.c_int)]
            lib.edge_Registry_staticmethod.restype = _runtime.Status
            lib.edge_Registry_throwOnDestroy.argtypes = [_edge_Registry_p, ctypes.c_bool]
            lib.edge_Registry_throwOnDestroy.restype = _runtime.Status
            lib.edge_Registry_fail.argtypes = [_edge_Registry_p]
            lib.edge_Registry_fail.restype = _runtime.Status
            lib.edge_Registry_liveCount.argtypes = [ctypes.POINTER(ctypes.c_int)]
            lib.edge_Registry_liveCount.restype = _runtime.Status
            _lib = lib
    return _lib


def add(arg1, arg2):
    """Wraps ``int edge::add(int, int)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().edge_add(
        _runtime.to_int(arg1, ctypes.c_int, "arg1"),
        _runtime.to_int(arg2, ctypes.c_int, "arg2"),
        ctypes.byref(_out),
    ))
    return _out.value


def combine(int32_t_, size_t_, EDGE_OK_):
    """Wraps ``int64_t edge::combine(int32_t int32_t, size_t size_t, int EDGE_OK)``."""
    _out = ctypes.c_int64()
    _runtime.check(_bind().edge_combine(
        _runtime.to_int(int32_t_, ctypes.c_int32, "int32_t_"),
        _runtime.to_int(size_t_, ctypes.c_size_t, "size_t_"),
        _runtime.to_int(EDGE_OK_, ctypes.c_int, "EDGE_OK_"),
        ctypes.byref(_out),
    ))
    return _out.value


def getattr(value):
    """Wraps ``int edge::getattr(int value)``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().edge_getattr(
        _runtime.to_int(value, ctypes.c_int, "value"),
        ctypes.byref(_out),
    ))
    return _out.value


def threading_():
    """Wraps ``int edge::threading()``."""
    _out = ctypes.c_int()
    _runtime.check(_bind().edge_threading(ctypes.byref(_out)))
    return _out.value


class Registry:
    """Wraps ``edge::Registry``.

    The C++ object is destroyed by close(), at the end of a ``with`` block or
    when this object is garbage collected, whichever comes first. Objects still
    alive when the interpreter exits are not destroyed.
    """

    __slots__ = ("__weakref__", "_finalizer", "_handle")

    def __init__(self):
        """Wraps ``edge::Registry::Registry()``."""
        if _builtins.getattr(self, "_finalizer", None) is not None:
            raise _builtins.TypeError("Registry object is already initialized")
        _handle = _edge_Registry_p()
        _runtime.check(_bind().edge_Registry_create(ctypes.byref(_handle)))
        self._adopt(_handle)

    def _adopt(self, handle):
        if not handle:
            raise _builtins.RuntimeError(
                "edge::Registry: the C layer returned a NULL handle"
            )
        self._handle = handle
        self._finalizer = weakref.finalize(self, _bind().edge_Registry_destroy, handle)
        # At interpreter exit, other threads may still be using the object.
        self._finalizer.atexit = False

    def _ptr(self):
        if not self._finalizer.alive:
            raise _builtins.ValueError("Registry object is closed")
        return self._handle

    def close(self):
        """Destroy the C++ object now. Calling it again does nothing."""
        finalizer = _builtins.getattr(self, "_finalizer", None)
        # detach() also works during interpreter shutdown, unlike calling the finalizer.
        pending = finalizer.detach() if finalizer is not None else None
        if pending is not None:
            _, destroy, arguments, _ = pending
            destroy(*arguments)

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        self.close()

    def __copy__(self):
        raise _builtins.TypeError("Registry objects cannot be copied")

    def __deepcopy__(self, memo):
        raise _builtins.TypeError("Registry objects cannot be copied")

    def __reduce__(self):
        raise _builtins.TypeError("Registry objects cannot be pickled")

    def classmethod(self):
        """Wraps ``int edge::Registry::classmethod() const``."""
        _out = ctypes.c_int()
        _runtime.check(_bind().edge_Registry_classmethod(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def staticmethod(self):
        """Wraps ``int edge::Registry::staticmethod() const``."""
        _out = ctypes.c_int()
        _runtime.check(_bind().edge_Registry_staticmethod(self._ptr(), ctypes.byref(_out)))
        return _out.value

    def throwOnDestroy(self, enabled):
        """Wraps ``void edge::Registry::throwOnDestroy(bool enabled)``."""
        _runtime.check(_bind().edge_Registry_throwOnDestroy(
            self._ptr(),
            _runtime.to_bool(enabled, "enabled"),
        ))

    def fail(self):
        """Wraps ``void edge::Registry::fail() const``."""
        _runtime.check(_bind().edge_Registry_fail(self._ptr()))

    @_builtins.staticmethod
    def liveCount():
        """Wraps ``static int edge::Registry::liveCount()``."""
        _out = ctypes.c_int()
        _runtime.check(_bind().edge_Registry_liveCount(ctypes.byref(_out)))
        return _out.value
