/* Generated by bridgefex from "counter.h". Do not edit. */
#ifndef DEMO_COUNTER_C_H
#define DEMO_COUNTER_C_H

#include "demo_runtime.h"

/* Opaque handles. In C++ they are the wrapped classes themselves. */
#ifdef __cplusplus
namespace demo {
class Counter;
}  /* namespace demo */
typedef ::demo::Counter demo_Counter;
#else
typedef struct demo_Counter demo_Counter;
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* demo::Counter::Counter() */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_create_void(demo_Counter** out_self);

/* demo::Counter::Counter(int32_t start) */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_create_int32(demo_Counter** out_self, int32_t start);

/* demo::Counter::~Counter() */
DEMO_API void demo_Counter_destroy(demo_Counter* self);

/* void demo::Counter::increment() */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_increment(demo_Counter* self);

/* void demo::Counter::add(int32_t delta) */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_add_int32(demo_Counter* self, int32_t delta);

/* void demo::Counter::add(double delta) */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_add_double(demo_Counter* self, double delta);

/* int32_t demo::Counter::value() const */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_value(const demo_Counter* self, int32_t* out_result);

/* bool demo::Counter::isZero() const */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_isZero(const demo_Counter* self, bool* out_result);

/* void demo::Counter::setLimit(int64_t limit) */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_setLimit(demo_Counter* self, int64_t limit);

/* int64_t demo::Counter::limit() const */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_limit(const demo_Counter* self, int64_t* out_result);

/* void demo::Counter::reserve(size_t bytes) */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_reserve(demo_Counter* self, size_t bytes);

/* void demo::Counter::fail() const */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_fail(const demo_Counter* self);

/* static size_t demo::Counter::liveInstances() */
DEMO_NODISCARD DEMO_API demo_status demo_Counter_liveInstances(size_t* out_result);

/* int64_t demo::multiply(int32_t a, int32_t b) */
DEMO_NODISCARD DEMO_API demo_status demo_multiply_int32_int32(int32_t a, int32_t b, int64_t* out_result);

#ifdef __cplusplus
}
#endif

#endif /* DEMO_COUNTER_C_H */
