// Generated by bridgefex from "counter.h". Do not edit.
#ifndef DEMO_C_API_BUILD
#define DEMO_C_API_BUILD
#endif

// The standard headers that the generated code needs come before the wrapped
// header, so that its macros cannot change them.
#include <cstddef>
#include <exception>
#include <new>
#if defined(__GLIBCXX__)
#include <bits/cxxabi_forced.h>
#endif

// The wrapped header comes before the generated ones: a global C++ declaration
// that clashed with a generated C function would then be a compile error, not a
// silent redirection.
#include "counter.h"

#include "counter_c.h"
#include "demo_runtime_internal.hpp"

#if !defined(__cpp_aligned_new)
// Before C++17, new ignores alignments larger than the default one of the
// platform's operator new.
namespace demo_detail {
#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
constexpr std::size_t new_alignment = __STDCPP_DEFAULT_NEW_ALIGNMENT__;
#elif defined(_MSC_VER) && defined(_WIN64)
constexpr std::size_t new_alignment = 16;  // std::max_align_t is double there
#else
constexpr std::size_t new_alignment = alignof(std::max_align_t);
#endif
}  // namespace demo_detail
static_assert(alignof(::demo::Counter) <= demo_detail::new_alignment,
              "demo::Counter is over-aligned: compile this file as C++17 or later");
#endif

extern "C" {

// demo::Counter::Counter()
demo_status demo_Counter_create_void(demo_Counter** out_self)
{
    if (out_self == nullptr) {
        return demo_detail::null_argument("demo_Counter_create_void: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return demo_detail::guard([&]() { *out_self = reinterpret_cast<demo_Counter*>(new ::demo::Counter()); });
}

// demo::Counter::Counter(int32_t start)
demo_status demo_Counter_create_int32(demo_Counter** out_self, int32_t start)
{
    if (out_self == nullptr) {
        return demo_detail::null_argument("demo_Counter_create_int32: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return demo_detail::guard([&]() { *out_self = reinterpret_cast<demo_Counter*>(new ::demo::Counter(start)); });
}

// demo::Counter::~Counter()
void demo_Counter_destroy(demo_Counter* self)
{
    // A destructor that throws cannot report it here, and last_error is left
    // alone because a failed call may not have been inspected yet.
    demo_detail::guard_silently([&]() { delete reinterpret_cast<::demo::Counter*>(self); });
}

// void demo::Counter::increment()
demo_status demo_Counter_increment(demo_Counter* self)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_increment: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::Counter*>(self)->increment(); });
}

// void demo::Counter::add(int32_t delta)
demo_status demo_Counter_add_int32(demo_Counter* self, int32_t delta)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_add_int32: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::Counter*>(self)->add(delta); });
}

// void demo::Counter::add(double delta)
demo_status demo_Counter_add_double(demo_Counter* self, double delta)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_add_double: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::Counter*>(self)->add(delta); });
}

// int32_t demo::Counter::value() const
demo_status demo_Counter_value(const demo_Counter* self, int32_t* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_value: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_Counter_value: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = reinterpret_cast<const ::demo::Counter*>(self)->value(); });
}

// bool demo::Counter::isZero() const
demo_status demo_Counter_isZero(const demo_Counter* self, bool* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_isZero: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_Counter_isZero: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = reinterpret_cast<const ::demo::Counter*>(self)->isZero(); });
}

// void demo::Counter::setLimit(int64_t limit)
demo_status demo_Counter_setLimit(demo_Counter* self, int64_t limit)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_setLimit: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::Counter*>(self)->setLimit(limit); });
}

// int64_t demo::Counter::limit() const
demo_status demo_Counter_limit(const demo_Counter* self, int64_t* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_limit: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_Counter_limit: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = reinterpret_cast<const ::demo::Counter*>(self)->limit(); });
}

// void demo::Counter::reserve(size_t bytes)
demo_status demo_Counter_reserve(demo_Counter* self, size_t bytes)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_reserve: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::Counter*>(self)->reserve(bytes); });
}

// void demo::Counter::fail() const
demo_status demo_Counter_fail(const demo_Counter* self)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_Counter_fail: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<const ::demo::Counter*>(self)->fail(); });
}

// static size_t demo::Counter::liveInstances()
demo_status demo_Counter_liveInstances(size_t* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_Counter_liveInstances: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::Counter::liveInstances(); });
}

// int64_t demo::multiply(int32_t a, int32_t b)
demo_status demo_multiply_int32_int32(int32_t a, int32_t b, int64_t* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_multiply_int32_int32: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::multiply(a, b); });
}

}  // extern "C"
