/* Generated by bridgefex. Do not edit. */
/* Runtime support shared by every header of the "demo" C API. */
#ifndef DEMO_RUNTIME_H
#define DEMO_RUNTIME_H

#include <stddef.h>
#include <stdint.h>
#ifndef __cplusplus
#include <stdbool.h>
#endif

/*
 * DEMO_API marks the exported functions. Define DEMO_STATIC when the C API
 * is built or used as a static library. The generated sources define
 * DEMO_BUILD themselves.
 */
#if defined(DEMO_STATIC)
#  define DEMO_API
#elif defined(_WIN32) || defined(__CYGWIN__)
#  if defined(DEMO_BUILD)
#    define DEMO_API __declspec(dllexport)
#  else
#    define DEMO_API __declspec(dllimport)
#  endif
#elif defined(__GNUC__) && __GNUC__ >= 4
#  define DEMO_API __attribute__((visibility("default")))
#else
#  define DEMO_API
#endif

/*
 * DEMO_NODISCARD asks the compiler to warn when a status is ignored: C++17
 * and C23 [[nodiscard]] (GCC 13/14 report C23 as 202000L), else the GNU
 * attribute, else nothing.
 */
#if defined(__cplusplus) && (__cplusplus >= 201703L || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L))
#  define DEMO_NODISCARD [[nodiscard]]
#elif !defined(__cplusplus) && defined(__STDC_VERSION__) && __STDC_VERSION__ > 201710L && defined(__has_c_attribute)
#  if __has_c_attribute(nodiscard)
#    define DEMO_NODISCARD [[nodiscard]]
#  endif
#endif
#if !defined(DEMO_NODISCARD) && defined(__GNUC__)
#  define DEMO_NODISCARD __attribute__((warn_unused_result))
#endif
#if !defined(DEMO_NODISCARD)
#  define DEMO_NODISCARD
#endif

/* Result of every function that can fail. */
typedef int32_t demo_status;

/* Success. */
#define DEMO_OK 0
/* The C++ code threw a std::exception; demo_last_error() has its what(). */
#define DEMO_ERROR_EXCEPTION 1
/* The C++ code threw something that is not a std::exception. */
#define DEMO_ERROR_UNKNOWN_EXCEPTION 2
/* A pointer argument was NULL. */
#define DEMO_ERROR_NULL_ARGUMENT 3
/* Memory allocation failed (std::bad_alloc). */
#define DEMO_ERROR_OUT_OF_MEMORY 4

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Message of the last error on the calling thread, in UTF-8 when the C++ code
 * uses UTF-8. Never NULL. Only meaningful right after a call that returned
 * something other than DEMO_OK: successful calls and destroy functions
 * leave it alone, and the next failing call on the same thread overwrites it.
 */
DEMO_API const char* demo_last_error(void);

/*
 * Fingerprint of this C API: it changes whenever a generated declaration
 * changes. Bindings compare it to detect a stale library.
 */
DEMO_API const char* demo_api_fingerprint(void);

#ifdef __cplusplus
}
#endif

#endif /* DEMO_RUNTIME_H */
