// Generated by bridgefex. Do not edit.
// Helpers for the generated C++ sources of the "demo" C API. Not part of
// the public API.
#ifndef DEMO_RUNTIME_INTERNAL_HPP
#define DEMO_RUNTIME_INTERNAL_HPP

#include "demo_runtime.h"

#include <exception>
#include <new>
#if defined(__GLIBCXX__)
// Only __cxxabiv1::__forced_unwind; <cxxabi.h> would also declare a global 'abi'.
#include <bits/cxxabi_forced.h>
#endif

namespace demo_detail {

#if !defined(__cpp_aligned_new)
// Alignment of the memory that operator new returns before C++17, which
// ignores larger alignments. <stddef.h> only: <cstddef> would declare
// std::byte.
#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
constexpr decltype(sizeof 0) new_alignment = __STDCPP_DEFAULT_NEW_ALIGNMENT__;
#elif defined(_MSC_VER) && defined(_WIN64)
constexpr decltype(sizeof 0) new_alignment = 16;
#elif defined(_MSC_VER)
constexpr decltype(sizeof 0) new_alignment = 8;
#else
constexpr decltype(sizeof 0) new_alignment = alignof(::max_align_t);
#endif
#endif

// Stores a copy of message as the last error of the calling thread.
void set_last_error(const char* message) noexcept;

inline demo_status null_argument(const char* message) noexcept
{
    set_last_error(message);
    return DEMO_ERROR_NULL_ARGUMENT;
}

// Runs function and turns any exception into a status code, so that no
// exception crosses the C boundary. The only exception let through is glibc's
// thread cancellation (pthread_cancel, pthread_exit), which must unwind its
// thread; swallowing it would abort the process.
template <typename Function>
demo_status guard(const Function& function)
{
    try {
        function();
        return DEMO_OK;
#if defined(__GLIBCXX__)
    } catch (__cxxabiv1::__forced_unwind&) {
        throw;
#endif
    } catch (const std::bad_alloc& error) {
        set_last_error(error.what());
        return DEMO_ERROR_OUT_OF_MEMORY;
    } catch (const std::exception& error) {
        set_last_error(error.what());
        return DEMO_ERROR_EXCEPTION;
    } catch (...) {
        set_last_error("unknown C++ exception");
        return DEMO_ERROR_UNKNOWN_EXCEPTION;
    }
}

// Runs function and ignores any exception (except a thread cancellation), for
// functions that cannot report errors.
template <typename Function>
void guard_silently(const Function& function)
{
    try {
        function();
#if defined(__GLIBCXX__)
    } catch (__cxxabiv1::__forced_unwind&) {
        throw;
#endif
    } catch (...) {
    }
}

}  // namespace demo_detail

#endif  // DEMO_RUNTIME_INTERNAL_HPP
