// Generated by bridgefex from "geometry.h". Do not edit.
#ifndef DEMO_C_API_BUILD
#define DEMO_C_API_BUILD
#endif

// The standard headers that the generated code needs come before the wrapped
// header, so that its macros cannot change them.
#include <cstddef>
#include <exception>
#include <new>
#if defined(__GLIBCXX__)
#include <bits/cxxabi_forced.h>
#endif

// The wrapped header comes before the generated ones: a global C++ declaration
// that clashed with a generated C function would then be a compile error, not a
// silent redirection.
#include "geometry.h"

#include "geometry_c.h"
#include "demo_runtime_internal.hpp"

#if !defined(__cpp_aligned_new)
// Before C++17, new ignores alignments larger than the default one of the
// platform's operator new.
namespace demo_detail {
#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
constexpr std::size_t new_alignment = __STDCPP_DEFAULT_NEW_ALIGNMENT__;
#elif defined(_MSC_VER) && defined(_WIN64)
constexpr std::size_t new_alignment = 16;  // std::max_align_t is double there
#else
constexpr std::size_t new_alignment = alignof(std::max_align_t);
#endif
}  // namespace demo_detail
static_assert(alignof(::demo::geometry::Circle) <= demo_detail::new_alignment,
              "demo::geometry::Circle is over-aligned: compile this file as C++17 or later");
#endif

extern "C" {

// double demo::multiply(double a, double b)
demo_status demo_multiply_double_double(double a, double b, double* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_multiply_double_double: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::multiply(a, b); });
}

// demo::geometry::Circle::Circle(double radius)
demo_status demo_geometry_Circle_create(demo_geometry_Circle** out_self, double radius)
{
    if (out_self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_create: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return demo_detail::guard([&]() { *out_self = reinterpret_cast<demo_geometry_Circle*>(new ::demo::geometry::Circle(radius)); });
}

// demo::geometry::Circle::~Circle()
void demo_geometry_Circle_destroy(demo_geometry_Circle* self)
{
    // A destructor that throws cannot report it here, and last_error is left
    // alone because a failed call may not have been inspected yet.
    demo_detail::guard_silently([&]() { delete reinterpret_cast<::demo::geometry::Circle*>(self); });
}

// double demo::geometry::Circle::radius() const
demo_status demo_geometry_Circle_radius(const demo_geometry_Circle* self, double* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_radius: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_radius: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = reinterpret_cast<const ::demo::geometry::Circle*>(self)->radius(); });
}

// double demo::geometry::Circle::area() const
demo_status demo_geometry_Circle_area(const demo_geometry_Circle* self, double* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_area: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_area: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = reinterpret_cast<const ::demo::geometry::Circle*>(self)->area(); });
}

// void demo::geometry::Circle::scale(double factor)
demo_status demo_geometry_Circle_scale(demo_geometry_Circle* self, double factor)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_scale: 'self' is NULL");
    }
    return demo_detail::guard([&]() { reinterpret_cast<::demo::geometry::Circle*>(self)->scale(factor); });
}

// double demo::geometry::distance(double x1, double y1, double x2, double y2)
demo_status demo_geometry_distance(double x1, double y1, double x2, double y2, double* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_distance: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::geometry::distance(x1, y1, x2, y2); });
}

}  // extern "C"
