/* Generated by bridgefex from "geometry.h". Do not edit. */
#ifndef DEMO_GEOMETRY_C_H
#define DEMO_GEOMETRY_C_H

#include "demo_runtime.h"

/* Opaque handles. */
typedef struct demo_geometry_Circle demo_geometry_Circle;

#ifdef __cplusplus
extern "C" {
#endif

/* double demo::multiply(double a, double b) */
DEMO_NODISCARD DEMO_API demo_status demo_multiply_double_double(double a, double b, double* out_result);

/* demo::geometry::Circle::Circle(double radius) */
DEMO_NODISCARD DEMO_API demo_status demo_geometry_Circle_create(demo_geometry_Circle** out_self, double radius);

/* demo::geometry::Circle::~Circle() */
DEMO_API void demo_geometry_Circle_destroy(demo_geometry_Circle* self);

/* double demo::geometry::Circle::radius() const */
DEMO_NODISCARD DEMO_API demo_status demo_geometry_Circle_radius(const demo_geometry_Circle* self, double* out_result);

/* double demo::geometry::Circle::area() const */
DEMO_NODISCARD DEMO_API demo_status demo_geometry_Circle_area(const demo_geometry_Circle* self, double* out_result);

/* void demo::geometry::Circle::scale(double factor) */
DEMO_NODISCARD DEMO_API demo_status demo_geometry_Circle_scale(demo_geometry_Circle* self, double factor);

/* double demo::geometry::distance(double x1, double y1, double x2, double y2) */
DEMO_NODISCARD DEMO_API demo_status demo_geometry_distance(double x1, double y1, double x2, double y2, double* out_result);

#ifdef __cplusplus
}
#endif

#endif /* DEMO_GEOMETRY_C_H */
