// Generated by bridgefex from "geometry.h". Do not edit.
#ifndef DEMO_BUILD
#define DEMO_BUILD
#endif

#include "geometry_c.h"
#include "demo_runtime_internal.hpp"

#include "geometry.h"

extern "C" {

// double demo::multiply(double a, double b)
demo_status demo_multiply_double_double(double a, double b, double* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_multiply_double_double: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::multiply(a, b); });
}

// demo::geometry::Circle::Circle(double radius)
demo_status demo_geometry_Circle_create(demo_geometry_Circle** out_self, double radius)
{
    if (out_self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_create: 'out_self' is NULL");
    }
    *out_self = nullptr;
    return demo_detail::guard([&]() { *out_self = new ::demo::geometry::Circle(radius); });
}

// demo::geometry::Circle::~Circle()
void demo_geometry_Circle_destroy(demo_geometry_Circle* self)
{
    try {
        delete self;
    } catch (...) {
        // A destructor that throws cannot report it here, and last_error is
        // left alone because a failed call may not have been inspected yet.
    }
}

// double demo::geometry::Circle::radius() const
demo_status demo_geometry_Circle_radius(const demo_geometry_Circle* self, double* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_radius: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_radius: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = self->radius(); });
}

// double demo::geometry::Circle::area() const
demo_status demo_geometry_Circle_area(const demo_geometry_Circle* self, double* out_result)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_area: 'self' is NULL");
    }
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_area: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = self->area(); });
}

// void demo::geometry::Circle::scale(double factor)
demo_status demo_geometry_Circle_scale(demo_geometry_Circle* self, double factor)
{
    if (self == nullptr) {
        return demo_detail::null_argument("demo_geometry_Circle_scale: 'self' is NULL");
    }
    return demo_detail::guard([&]() { self->scale(factor); });
}

// double demo::geometry::distance(double x1, double y1, double x2, double y2)
demo_status demo_geometry_distance(double x1, double y1, double x2, double y2, double* out_result)
{
    if (out_result == nullptr) {
        return demo_detail::null_argument("demo_geometry_distance: 'out_result' is NULL");
    }
    return demo_detail::guard([&]() { *out_result = ::demo::geometry::distance(x1, y1, x2, y2); });
}

}  // extern "C"
